### ISSUE TITLE
Count number of people watching

### ISSUE THREAD

**Issue by ivanjunckes** [datarhei/restreamer#100]
Is there a way that Restreamer shows the number of people watching a video simultaneously? It can be either in the player or in an API.

**Comment by ioppermann** [comment]
Hi Ivan

This is currently not implemented, and I will put it on the feature request list.

**Comment by ivanjunckes** [comment]
Thanks @ioppermann

**Comment by br0kenlink** [comment]
yes, this feature would be greatly appreciated

**Comment by br0kenlink** [comment]
Is there any other way I can find out current number of people watching at this moment?

**Comment by ma0dubois** [comment]
a good solution can be found here: https://github.com/arut/nginx-rtmp-module/wiki/Getting-number-of-subscribers

**Comment by ioppermann** [comment]
@ma0dubois Thanks for the hint. However, this only refers to the number of subscribers to the RTMP stream. The Restreamer player is using HLS which is served via HTTP.

nginx has the status module which gives the number of active HTTP connections, but this is not very accurate because a browser may open serveral connections to the server.

**Comment by ma0dubois** [comment]
> @ma0dubois Thanks for the hint. However, this only refers to the number of subscribers to the RTMP stream. The Restreamer player is using HLS which is served via HTTP.
> 
> nginx has the status module which gives the number of active HTTP connections, but this is not very accurate because a browser may open serveral connections to the server.

arf  :/
Can you explain your plan for this ?
Create an interval ajax in the player.html ?

**Comment by ioppermann** [comment]
Depending on the accuracy requirments you have, there might be different solutions. The one I mentioned before would give a number which is probably a rough approximation of the actual current viewers and should be the easiest to implement.

Another way could be via session cookies, but cookies are not so popular (GDPR) and not reliable with all the existing privacy features the browsers implement.

Or you could check from how many IPs the .m3u8 file gets downloaded. There you have to consider NATs. The resulting number will be probably lower than the actual number of viewers but still a very good approximation. This could be implemented with e.g. some LUA scripting inside nginx.

Even another option would be to add a UUID as query string to the .m3u8 file in the player.html, then you track how many UUIDs are currently used (similar to the IP approach). This sould give a quite accurate number of viewers, given that they use the player.html and don't pull the stream directly.

The interval ajax would also give you only the number of viewers that use the player.html and there you also have to distinguish them (e.g. by cookie, UUID, ...).

There are some options available, where the "IP counting" method seems to be most viable to me.

**Comment by barbrastreisand** [comment]
Shame this isn't an existing feature. The laws/licensing that would apply to our livestreaming project would require accurate current and past numbers of people watching. I'm not much of a dev/admin so don't quite understand how to implement the suggestions above, or if they would give us accurate numbers. Great project though, so will def keep an eye on this to see if an official feature is ever developed.

**Comment by ioppermann** [comment]
We are currently working on this feature and are evaluating the different options.

**Comment by wallopthecat** [comment]
`stub_status;` seems like an easy one if accuracy is not paramount

**Comment by maiksd** [comment]
> `stub_status;` seems like an easy one if accuracy is not paramount
> 
> EDIT: for anyone who wants to do this:
> https://github.com/wallopthecat/restreamer/tree/status

I just tried this. Nice addition in general, but not suited for low numbers of viewers. I already have 16 connections after starting the stream and adding just myself as a viewer. Added a second viewer, waited a while, down to 11. Not very reliable unfortunately. Of course it's totally up the browser of each viewer how much connections it opens to fetch hls portions.

**Comment by RaymiiOrg** [comment]
I'm using a brute force setup as described on the bottom here: https://raymii.org/s/snippets/Get_number_of_incoming_connections_on_specific_ports_with_ss.html

If you want to measure long running connections, a somewhat working example is
the following:

    comm -1 -2 <(ss --all --numeric --no-header state established  '( sport = :443 )' | awk '{print $5}' | awk -F:  'NF{--NF};1' | sort -u) <(sleep 5; ss --all --numeric --no-header state established  '( sport = :443 )' | awk '{print $5}' | awk -F:  'NF{--NF};1' | sort -u) | wc -l

The `comm` command is a reverse `diff` (show all things in common), `-1` and
`-2`. The command executed is the same, only the last command has a `sleep 5`
in front of it:

    ss --all --numeric --no-header state established  '( sport = :443 )' | awk '{print $5}' | awk -F:  'NF{--NF};1' | sort -u

It prints all established connections to port 443, strips out the part after
the last colon (the two awk commands) so that it works with IPv6 as well and
then sort the list, removing duplicates. NATted connections will be counted 
once.

This way, you get all IP addresses that have an established connection for at
least 5 seconds in your graph. 

Port 443 is nginx that is in front of restreamer as a reverse proxy. Users connect to there, not to port 8080. If you don't run a reverse proxy, change the port.

**Comment by RaymiiOrg** [comment]
I've written some more on how to measure viewers, if anyone is interested :  https://raymii.org/s/tutorials/Semi-accurate_live_stream_viewer_count.html

**Comment by jstabenow** [comment]
Hey guys,
Your problems should be solved with the latest release:
- Current viewers and bandwidths
- Bandwidth limitation
- Viewer/Session limitation

More informations:
- https://docs.datarhei.com/restreamer/knowledge-base/manual/system-settings/network#bandwidth-control
- https://demo.datarhei.com/api/swagger/index.html#/default/session-3-current
- https://demo.datarhei.com/api/swagger/index.html#/default/restream-3-get-all

Check it out and post if you have any questions.
