### ISSUE TITLE
Multiple external providers simultaneously?

### ISSUE THREAD

**Issue by mcrypt** [datarhei/restreamer#122]
Is it currently possible to forward one rtmp stream to multiple external streaming providers simultaneously?

**Comment by ioppermann** [comment]
@mcrypt Currently, you can only forward the stream to one provider. In the future we want to support more than one forwarding.

**Comment by a93h** [comment]
@ioppermann  You lie 😉 
I hacked my own rtmp module.
4 containers.
2 inputs
2 outputs.

**Comment by a93h** [comment]
@mcrypt 

You can stream using an ffmpeg one-liner.

I would research exact details for your use-case.

**Comment by ioppermann** [comment]
@a93h I interpreted the question in way that @mcrypt wanted to know if this is possible with only one Restreamer container. The solution with multiple Restreamer container is documented (https://datarhei.github.io/restreamer/docs/guides-multiple-restreamer.html).

Multi-Streaming with an ffmpeg one-liner is sure possible, however if one output fails, it will also stop the other ones because ffmpeg will exit in this case.

**Comment by radumalica** [comment]
You can do it like this:
1. install one docker container , configure your input stream with optional output stream (1st one).
2. deploy second container, setting the input stream from the first container (rtmp://IP_OF_FIRST_DOCKER/live/external.stream?token=...) and setup optional output to second streaming platform you want. 

Basically instead of setting rtmp://localhost to see your stream, you get it from the first docker container where the original stream is pushed.

You can deploy this way multiple containers, 1 for each output platform getting the input from the first container, or cascading them if they are installed on different servers.

I would love to learn some angular JS and modify this directly into the software and set multiple optional fields there, eventually saving them / editing in the future if the token changes so you don't have to type everytime the URLs and tokens.

Or the simpler method (haven't tested it) . Hardcode the push directive into original nginx.conf to as many streaming platforms as you want and don't enable optional output. Not sure if the software overwrites something in nginx.conf on the fly so these directives might disappear.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
