### ISSUE TITLE
Password issue

### ISSUE THREAD

**Issue by jacobq11** [datarhei/restreamer#127]
I figured I should let you know when installing the container using the instructions here, passwords with special characters do not work. For example, the password "T3st!ng" returns 

```
root@minetlancore:~# docker run -d --restart always --name restreamer -e "RS_USERNAME=admin" -e "RS_PASSWORD=T3st!ng" -p 8080:8080 -v /mnt/docker/restreamer/db:/restreamer/db  datarhei/restreamer:latest 
-bash: !ng: event not found
```

**Comment by ioppermann** [comment]
Hi @jacobq11, thanks for the hint. However this is not an issue with Restreamer but with bash shell. bash is trying to interpret the `!`. In this case you have to escape it with `\` in order to tell bash to ignore it, i.e. `...  -e "RS_PASSWORD=T3st\!ng"  ...`. The `\` wil not be part of the password.

https://www.tldp.org/LDP/Bash-Beginners-Guide/html/sect_03_03.html
