### ISSUE TITLE
Embeded Player HTTPS

### ISSUE THREAD

**Issue by advantix78** [datarhei/restreamer#136]
Hello everyone,
The purpose of this discussion is to understand how to embed the player on an HTTPS website.
By installing Restreamer on a VPS everything is normally ok, but when you copy the (IFRAME) to the site it does not appear because it is in HTTP and not HTTPS.
I'm trying to install Restreamer on a VPS in HTTPS mode.
The VPS has Ubuntu, and as a guide I install the docker, after which the speech of the certificate is not clear to me.
First of all, should the certificate be that of the destination website, or should a certificate be created specifically for inclusion in the VPS?
Is there any tutorial on that that explains well the steps to be performed in order to use the player directly on the site?
Thank you

**Comment by ioppermann** [comment]
Hi @advantix78 

This is correct, that you can iframe only HTTPS content into a site that is HTTPS.

The certificate for the Restreamer should be the one of the VPS. If your site is on `www.example.com` and you set the DNS record for the subdomain `stream.example.com` to point to your VPS, then you need a certificate for `stream.example.com`. Then you can iframe `https://stream.example.com/player.html` into `https://www.example.com`.

How do you get a certificate for your VPS? Restreamer requires that you already have a certificate in order to run in HTTPS mode or you put a nginx in front of Restreamer, then nginx can handle the HTTPS stuff. (https://datarhei.github.io/restreamer/docs/guides-https.html and https://datarhei.github.io/restreamer/docs/guides-proxying.html).

To have nginx in front of the Restreamer and use the Let's Encrypt certbot (https://certbot.eff.org/) for obtaining the certificate and configuring nginx accordingly is the recommended solution because you will not need to restart Restreamer in order to load the renewed certificates. You only need to reload the nginx that is sitting in front of Restreamer. 

There are many tutorial available how to use Let's Encrypt certificates with nginx on Ubuntu, e.g. https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04 . Then forwarding the requests to Restreamer is only a matter of configuring nginx accordingly (https://datarhei.github.io/restreamer/docs/guides-proxying.html).

**Comment by advantix78** [comment]
I managed to install the certificates on a VPS with Let's Encrypt, only that it creates another nginx server on the machine and when I type the address on the web this opens.
How do I redirect to the restreamer's nginx? (PROXY?).
Or where is the restreamer nginx folder?
I always state that I am not an expert and perhaps they are trivial questions. Thank you

**Comment by advantix78** [comment]
![ssl](https://user-images.githubusercontent.com/40419553/79976100-64417f00-849c-11ea-8fc1-09f9a811a3c3.jpg)
With a little patience and a little time I did it. Thank you

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
