### ISSUE TITLE
Add VA-API hardware acceleration option to restreamer

### ISSUE THREAD

**Issue by redrob** [datarhei/restreamer#137]
Hi there,

Our non-profit outfit really appreciates the efforts you have put into restreamer, thank you. We use it to restream an outdoor camera to Youtube. 

One capability I am looking for is VA-API hardware encoding capabilities. I have been trying to build my own docker image based on this repo but with "--enable-vaapi \" added to ffmpeg configure options in Dockerfile. Unfortunately, that threw an error when i attempted to build the docker imge;

ERROR: vaapi requested but not found

I am pretty new to docker still but it would be great if this was added to rs natively. 

Thanks again!

**Comment by ioppermann** [comment]
@redrob Please check this issue in order to use the VA-API in the Docker containter: https://github.com/datarhei/restreamer/issues/128

**Comment by redrob** [comment]
Hi @ioppermann Yeah I did try that. Though that is quite a hack and seems to be centrically geared to Synology type devices. 

Thanks though...

**Comment by LckyLuciano** [comment]
Hi @redrob I was able to get vaapi encoding working on non-Synology hardware today.  You might want to take a look here:  
https://github.com/datarhei/restreamer/issues/128#issuecomment-775559396

**Comment by redrob** [comment]
> Hi @redrob I was able to get vaapi encoding working on non-Synology hardware today. You might want to take a look here:
> [#128 (comment)](https://github.com/datarhei/restreamer/issues/128#issuecomment-775559396)

Thanks LckyLuciano, will give it a shot

**Comment by jstabenow** [comment]
Hey @redrob 
Please test the latest `datarhei/restreamer:vaapi-latest` Docker image. Should work.

**Comment by svenerbeck** [comment]
Hi @redrob 
We are closing your issue https://github.com/datarhei/restreamer/issues/137.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
//Sven
