### ISSUE TITLE
HTTPS - Nginx Can't load certificate 

### ISSUE THREAD

**Issue by Grandshort** [datarhei/restreamer#188]
I've followed the steps to get HTTPS working on my system, but when i go to start up Restreamer,   I get an error message saying that Nginx can't load the certificate because it can't find it. 

if i go to the path where is expecting to find it  ( '/restreamer/conf/../db/ssl/cert.pem' ) in the docker container, it can see it

`docker run -p 443:8181 -e RS_HTTPS=true datarhei/restreamer

[21-07-2020 08:30:47.877] [INFO ] [                   ENV] RS_HTTPS = true - Enables HTTPS support for admin interface and embeddable player.
[21-07-2020 08:30:47.877] [INFO ] [                   ENV] RS_INPUTSTREAM =  (using default) - Automatically start pulling from this stream on a fresh Restreamer installation.
[21-07-2020 08:30:47.878] [INFO ] [                 NGINX] Starting ...
[21-07-2020 08:30:47.878] [INFO ] [                 NGINX] Enabling HTTPS
**[21-07-2020 08:30:47.902] [ERROR] [                 NGINX] cannot load certificate "/restreamer/conf/../db/ssl/cert.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/restreamer/conf/../db/ssl/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)**
[21-07-2020 08:30:47.904] [ERROR] [                 NGINX] Exited with code: 1
[21-07-2020 08:30:48.143] [ERROR] [                 start] Error starting webserver and nginx for application: Error: Failed to start`

**Comment by ioppermann** [comment]
@Grandshort The certificate files need to be available inside the docker container. You still have to mount the directory with the certificate files into the container. From the documentation:

> Place the certificate and key file as cert.pem and key.pem in a subdirectory called ssl into the directory that you mount to /restreamer/db, [...].

See: https://datarhei.github.io/restreamer/docs/guides-https.html

What this means is, from the basic setup (e.g. https://datarhei.github.io/restreamer/docs/installation-linux-64.html), you have the command `docker run -d --restart always --name restreamer -e "RS_USERNAME=..." -e "RS_PASSWORD=..." -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db datarhei/restreamer:latest`. The directory `/mnt/restreamer/db` is locally on your computer and will be mounted as `/restreamer/db` into the container.

In order to have the certificate file available inside the container, copy the `key.pem` and `cert.pem` to `/mnt/restreamer/db/ssl`, so you'll have `/mnt/restreamer/db/ssl/key.pem` and `/mnt/restreamer/db/ssl/cert.pem`. Then modifiy the docker command, such that Restreamer enables HTTPS:

```
docker run -d --restart always \
     --name restreamer \
     -e "RS_USERNAME=..." -e "RS_PASSWORD=..." \
     -p 8080:8080 -v /mnt/restreamer/db:/restreamer/db \
     -p 443:8181 -e RS_HTTPS=true \
     datarhei/restreamer:latest
```

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
