### ISSUE TITLE
Building a Script Stack for portainer.io

### ISSUE THREAD

**Issue by Thiagobhmg** [datarhei/restreamer#191]
You could write a stack to upload a container with all the settings needed to raise a server with restreamer. It would be very useful

**Comment by svenerbeck** [comment]
Hello 

We are closing your ticket https://github.com/datarhei/restreamer/issues/366.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
