### ISSUE TITLE
Snapshot interval question

### ISSUE THREAD

**Issue by marcaddeo** [datarhei/restreamer#199]
👋🏻 

I was just wondering if there's a technical reason to disallow snapshot intervals lower than `10s`. I'd like to have real time snapshots with Restreamer, but it's not possible currently.

**Comment by ioppermann** [comment]
The reason for this minimal interval is, that for each snapshot a new ffmpeg process is started in order to extract a frame. In order not unnecessarly load the system with extracting a frame (i.e. connecting to the stream, decoding one frame, writing that frame as JPG, disconnecting from the stream), this limit has been set.

If you want you can change the limit in the source code https://github.com/datarhei/restreamer/blob/master/src/classes/Restreamer.js#L160 and build your own Docker image.

In order to have a real time snapshot (what is real time for you? You can only go as low as every frame) you would need to decode the stream all the time and permanently saving it as a JPG, which would cause some I/O load.

**Comment by jstabenow** [comment]
Hey @marcaddeo 
The Release v2 includes an Image2 publication service. Have fun with it.
