### ISSUE TITLE
RTMP OBS Nvenc Issues

### ISSUE THREAD

**Issue by badincite** [datarhei/restreamer#222]
Anyone else having issues ingesting rtmp out of obs using the nvidia nvenc codec? I had it working at one point now its inconsistent. I can get is going sometimes switching the bitrate type cbr to vbs around after I start the stream. Ive tired different versions of obs,nvidia drivers, and also v0.6.6 of restreamer not sure where the issues is.

**Comment by badincite** [comment]
Issue was the keyframe interval leaving it on default 0=auto causes the video not to be accepted.

**Comment by ioppermann** [comment]
Yes, setting the keyframe interval is crucial. Depending on the content, the encoder may decide to add a keyframe e.g. only every 30 seconds. This has several implications:

1. For live streaming a constant and short keyframe interval is wanted because it is possible to open the stream at any time. The player can only start playing the stream after the first keyframe it encounters. If the keyframe interval is too long or varies, the latency until the user actually sees something is probably unacceptable.

2. By sending the stream from OBS to Restreamer via RTMP, Restreamer will probe the stream from its local RTMP server that is ingesting the stream from OBS. ffmpeg probes the stream by actually reading the first few seconds of the stream in the hope that it will find useable data (the keyframe) in the stream. If the keyframe interval is too long it may happen that ffmpeg never sees a keyframe and aborts the probe unsuccessfully after a few seconds.

A good value for the keyframe interval is 2 seconds: https://datarhei.github.io/restreamer/docs/guides-obs.html
