### ISSUE TITLE
How to secure HLS stream

### ISSUE THREAD

**Issue by arcadiush** [datarhei/restreamer#225]
Hello,
I provide the image from cameras on the website via iframe. How can I hide the Restreamer login page from others and prevent streaming from stealing the link from the browser ?

**Comment by ioppermann** [comment]
@arcadiush In order to hide the UI of the Restreamer you could put a nginx in front of it that only passes the requests that are required for embedding the player, or only the files required for streaming (i.e. the /hls directory). Then where ever you want to show the stream you can use any player that is able to play HLS content. You are not bound to the player that comes with Restreamer.

For securing the stream (i.e. preventing from stealing it), there's currently no out-of-the-box solution. I think it would be feasible to make this work with user sessions. The idea is, that if someone loads the player.html, it creates a session (with a timeout) and sets a cookie. This cookie will then also be sent while requesting the m3u8 file (given that the player.html is served from the same domain as the m3u8 file). Before returning the m3u8 file, the provided session is checked. If the session is ok, the m3u8 gets delivered, if not it will return a 403 (access denied). This means, that only a client who has access to the player.html will get a valid session ID and will be able to load the m3u8. A client (e.g. VLC) which tries to access the m3u8 directly will be rejected.

But how to implement this? My spontaneous idea is to have nginx with the lua module (https://github.com/openresty/lua-nginx-module) in front of the Restreamer. With lua you can intercept the calls to the player.html and m3u8. So, if someone calls player.html a lua script running in nginx kicks in and creates a new session or refreshes an existing session (the session can be stored in memory in a map or so) and sets the cookie. If the m3u8 is requested, another lua script kicks in and the session cookie is checked if it is valid.

This would involve cookies. To do it without cookies, it might be possible to replace the name of the m3u8 file with the session ID before sending the player.html to the client (I think this can also be done with the lua module). Then when the m3u8 is requested, the session ID in its name is checked if the is valid and the m3u8 is delivered.

The m3u8 itself contains URLs to the actual video data (.ts files). These names change constantly for each video segment that is created and can't be guessed. So these don't need to be protected. But if you want this too, you could rewrite the contents of the delivered m3u8 such that the names of the .ts file also contain the session ID. When the .ts file is requested you can check again the session ID and deliver the actual .ts file.

These are just some rough ideas without any guarantee that it will work like this or if it will be really possible to implement it with the mentioned lua module. But I hope it points into the right direction.

With the upcoming releases of Restreamer we're planning to have such (or a similar) solution integrated.

Please also check https://github.com/datarhei/restreamer/issues/183

**Comment by badincite** [comment]
Definitely like this idea! I was just surfing instants of restreamer using a certain website and I was able to view multiple cameras.

**Comment by z8rsvenbergner** [comment]
I use Traefik to prevent all unwanted Traffic to the Container.
Also secured with Cloudflare and it workes fine!

Only the Image is provided under an URL,
and on the second URL is the seperated Stream.

**Comment by svenerbeck** [comment]
Thank you very much for your comment. We have implemented the function in the Restreamer v2 🚀
Have fun with it.
