### ISSUE TITLE
Add additional Stream To SRT 

### ISSUE THREAD

**Issue by shihan84** [datarhei/restreamer#287]
hi requesting to add 1 more format SRT like rtmp and hls please

**Comment by ioppermann** [comment]
SRT support will be available in the next release.

**Comment by FilipStadler** [comment]
I have been looking on howto make it work on restreamer but I am not a programmer ;)
 - should be easy to make it work when the ffmpeg supports it,
 
ffmpeg -i "srt://:1935?mode=listener&passphrase=somekeyword" -c copy -f flv rtmp://127.0.0.1:1935/something.

This would wait for a caller but we cant be sure -c copy is h264 so maybe other options would be needed 
but currently i just do it with systemd - i have also tried with srt-live-transmit tool but this cant do rtmp
only udp or srt - but I dont think the restreamer wiill accept udp but we may also need to translate input
so ffmpeg maybe best solution to use anyway - also the nginx need to do its stuffe with a stream.


I have not tried RIST but it looks simular

**Comment by OscarParzon** [comment]
> La compatibilidad con SRT estará disponible en la próxima versión.

Hello !.
in version 2.0 there is no SRT?

**Comment by FilipStadler** [comment]
> > La compatibilidad con SRT estará disponible en la próxima versión.
> 
> Hello !. in version 2.0 there is no SRT?

It have SRT for outgoing - but I am not sure how to set up srt input - I have not found it maybe I have to select pull mode in networks and the add srt with mode=listener - I am not sure where to find it...  also it uses UDP but it should be possible to replace rtmp with srt - anyway transmission outgoing streams with srt is nice and this is working.

**Comment by jstabenow** [comment]
@OscarParzon @FilipStadler 
True. Currently, SRT can only transmit. 
We could build the receive mode into the component and start the container with additional ports so that FFmpeg can use them. That should be possible. Would that be a solution?

**Comment by FilipStadler** [comment]
ffmpeg -i "srt://0.0.0.0:{1935}?mode=listener&latency=120000&passphrase=somekeyword" -c copy -f flv rtmp://127.0.0.1:{1935}/something.

Would it not be possible to add srt like it was rtsp pull - I don't understand why its not possible but yes srt uses udp but this also possible with rtsp it looks like so - but yes its nice restreamer but srt listenermode would be so usefull.

Its possible to run the ffmpeg outsite the container so it can handle both rtmp or srt but I don't understand the problem on how to implement it.  The Transmission part is great implemented.

One strange thig was that I was not able to srt out to srt://127.0.0.1:5000 but to other destinations was possible,
Why localy because I have OBS on the same computer running the restreamer but non local destinations was working.

Using h265/hvec is also better on srt and if one do -c copy to rtmp it can be a problem for the rtmp.

Its the only small but important thing missing in the restream.

**Comment by jstabenow** [comment]
1. SRT has several modes:
https://ffmpeg.org/ffmpeg-protocols.html#srt

- caller = create a camera (srt://....)
- rendezvous = create a SRT publication service
- listener = currently not supported

2. under Linux you could work with `docker --net=host`. However, this is not possible under Win/OSX.
=> We are thinking about integrating the listerer mode. 

3. for the output you have to use another address (e.g. the real host IP). 127.0.0.1 / localhost is inside the container.

4. we will take care of H.265 soon. This was not a requirement for the release. 
=> But you are right.

**Comment by jstabenow** [comment]
Hello @shihan84 
The v2.2.0 now supports SRT listening (server). Here is a tutorial for OBS via SRT > Restreamer:
https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-to-stream-srt-from-obs

We are looking forward to your feedback.
