### ISSUE TITLE
Add audio track to existing RTSP stream.

### ISSUE THREAD

**Issue by b3nscher** [datarhei/restreamer#314]
Hey, 

I'm currently using the Jetson Nano with Restreamer to intercept my camera signal which comes from a Sony a6000 via Wifi module over RTSP stream and forward it to Twitch. 

This works fine without any losses, but I would like to have the sound of my microphone in the stream. This microphone is connected via jack to a USB sound card. 

How could I best integrate this signal?  

best regards

**Comment by svenerbeck** [comment]
Please check this with the Restreamer v2 🚀. We would be happy to receive feedback.

**Comment by svenerbeck** [comment]
Hi @b3nscher 
We are closing your issue https://github.com/datarhei/restreamer/issues/314.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
//Sven
