### ISSUE TITLE
Update Restreamer to support FFMPEG v5

### ISSUE THREAD

**Issue by utilsites** [datarhei/restreamer#322]
The latest major version of [FFMPEG ](https://ffmpeg.org/download.html) is v5, and restreamer is only compatible with version 4.x.
It seems that v5 is not compatible with the args used in restreamer.
Can restreamer be updated to support FFMPEG v4 and v5, and prevent in a hurry changes in the future due to new requirements for new iOS version for example?

We noticed that we had to update FFMPEG to latest v4.x version to the livestream works on iOS 15.4+.

**Comment by svenerbeck** [comment]
Hi [utilsites](https://github.com/utilsites)
We have prepared the update FFmpeg v5. You can already see it in the latest [changelog](https://github.com/datarhei/restreamer/releases/tag/v.2.1.0.)

Keep an eye out for updates coming soon. We will then close the ticket.

🤝 [electronic high5]
Sven

**Comment by utilsites** [comment]
Thanks for the info, but that is for the Restreamer 2.x, on Restreamer 0.x can't update to FFmpeg v5?
We want to migrate to v2 in the future, the migration is so easy like described [here](https://docs.datarhei.com/restreamer/installing/update#migration-from-v.0.x-to-v.2.x)  ?
When we search "Restreamer" on google it takes us to old version and there is no link to the new version? It's a bit confusing. It's different teams?
Thanks

**Comment by svenerbeck** [comment]
Hey Ho [utilsites](https://github.com/utilsites)
We can only provide support from version 2. There we have a comprehensive system for logging and server reports and many other things that make reliable support possible for professional use cases. Thank you for your understanding.

> We want to migrate to v2 in the future, the migration is so easy like described [here](https://docs.datarhei.com/restreamer/installing/update#migration-from-v.0.x-to-v.2.x) ?

Yes Sir! It is that easy. :) 

> When we search "Restreamer" on google it takes us to old version and there is no link to the new version? It's a bit confusing. It's different teams?

No, it is our software and the same team ([http://foss-gmbh.ch](http://foss-gmbh.ch/index_en.html)). Because the new version is only available since mid-May, Google has probably not yet indexed properly. This needs a little time. But you are definite right! There needs to be a bold mark on the old website. We will update this. These are the one and only current docs: https://docs.datarhei.com/restreamer/

🤝 [electronic high5]
Sven
