### ISSUE TITLE
Hardware support for Nvidia CUDA

### ISSUE THREAD

**Issue by FilipStadler** [datarhei/restreamer#328]
Unable to find image 'datarhei/restreamer:cuda-latest' locally
docker: Error response from daemon: manifest for datarhei/restreamer:cuda-latest not found: manifest unknown: manifest unknown.

I looks like its not available now ?

**Comment by jstabenow** [comment]
Hey @FilipStadler 
Release v2.1.0 is out now and the CUDA build is fixed. Thanks for your hint 👍
Please note: `NVIDIA_REQUIRE_CUDA=cuda>=11.4`

**Comment by maykel535** [comment]
Hi, I have rtx 4090 with cuda version 12:

| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |

The docker has cuda 11.7. In the step "video device hardware" (no input device available)

The problem is the version of cuda? I like enconding with GPU.

Thanks in advanced and great work!
