### ISSUE TITLE
restreamer with OBS on the same system does not work

### ISSUE THREAD

**Issue by FilipStadler** [datarhei/restreamer#333]
I can't make a SRT caller stream to the local computer - normaly it would be possible using 127.0.0.1:6006 but does not work
even if I replace the IP with non local ip like 192.168.10.192 it cant handle this - it looks like it tryes but fail.
I can from another restreamer connect to the 192.168.10.192:6006 and it works without anye problems.

I know I can pull the stream using HLS to get it into OBS on the same computer - I just don't understand why it cant.
And its not only OBS It cant make connection with using SRT.

**Comment by jstabenow** [comment]
Hey @FilipStadler,
You know, the Restreamer can currently only pull and push SRT streams. However, OBS sends via SRT, which presently does not work.

If you want to use OBS with the Restreamer, please use RTMP. Here is a setup guide:
https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-receive-an-rtmp-stream#receiving-video-source-via-rtmp-using-obs-as-an-example

And please let's discuss SRT in the existing tickets. Otherwise, it is too distributed.
