### ISSUE TITLE
the channel names

### ISSUE THREAD

**Issue by ftrescue** [datarhei/restreamer#362]
![image](https://user-images.githubusercontent.com/96438569/173275340-1d5f3679-2e5c-49bb-a334-e2d5350831b6.png)

And when I go back in and put them on save button not working ??
any ideas how to fix please thanks

**Comment by svenerbeck** [comment]
Hello ftrescue
You have described something little about what your request is. So I interpret that you would like to customize the channel names, which does not work as expected? 

Take a look at this [doc](https://docs.datarhei.com/restreamer/knowledge-base/manual/edit-livestream/meta-information). 

**Navigate to:**

1. Stream Settings ([4](https://docs.datarhei.com/restreamer/knowledge-base/manual/main-screen))
2. Meta Information ([4](https://docs.datarhei.com/restreamer/knowledge-base/manual/edit-livestream))
3. Enter the details and **don't forget to save**.
![Enter the details and don't forget to save.](https://2422329260-files.gitbook.io/~/files/v0/b/gitbook-x-prod.appspot.com/o/spaces%2F-MS3qj4cW170AMeE1ckj-1703796690%2Fuploads%2FaZPSyjZoY5r2SBdERZSv%2Fstream-conf-metadata.png?alt=media&token=645e9df3-9b30-43ad-9f59-3b86f8a81695)

We need log files from your host system if this does not work. Please get in touch with us then.

Greetings from datarhei.com
Sven

**Comment by ioppermann** [comment]
When you change a channel name, you also have to re-save the playersite. Otherwise the channel name will not be updated on the playersite.

**Comment by svenerbeck** [comment]
Thank you Ingo
So you found a kind of Bug [ftrescue](https://github.com/ftrescue)
Thank you for the advice. We will fix this in the next update.
Cheerio
Sven

**Comment by svenerbeck** [comment]
Hello @ftrescue 
We are closing your issue #362.

This may be due to the following reasons:

Problem/inquiry has been solved
Ticket remained unanswered by you for a longer period
Problem was explained and handled in another ticket
You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
