### ISSUE TITLE
how to run this project locally without using docker

### ISSUE THREAD

**Issue by devsecops1solution** [datarhei/restreamer#364]
hi everybody i hope you are doing well so i would like to run this project locally in an offline network without using docker

**Comment by svenerbeck** [comment]
Hi @devsecops1solution
Native installation is possible, but not officially supported by us at the moment. It is because the installation has too many pitfalls. However, we are already working on a solution for native installation. 
I'll be honest, and it's not a big priority now. So I wouldn't count on it this year.

Please get in touch with us if it's essential to you for a commercial project. Then we will provide you with a software developer to support you in getting it running.  That would be, depending on your project, Tier 1 ([Sponsor](https://www.patreon.com/datarhei)) or 2 levels ([Benefactor](https://www.patreon.com/datarhei)).

If you have any questions about the Support levels, don't hesitate to contact us at support@datarhei.com.

Cheerio
Sven

**Comment by jstabenow** [comment]
You can find installation instructions in the Dockerfiles:

The Restreamer bundle (combines Restreamer-UI, Core, FFmpeg):
https://github.com/datarhei/restreamer/blob/2.x/Dockerfile

The Restreamer-UI built:
https://github.com/datarhei/restreamer-ui/blob/main/Dockerfile

The Core (Backend) build:
https://github.com/datarhei/core/blob/main/Dockerfile

And you have to compile FFmpeg with our patch:
https://github.com/datarhei/ffmpeg/tree/4.4/contrib

Unfortunately, that's all the help we can offer now. Alternative installations are on the roadmap. But without priority.

If you have other questions, please open a new issue.
Thanks.
