### ISSUE TITLE
unable to stream to owncast

### ISSUE THREAD

**Issue by Restreamdev** [datarhei/restreamer#369]
i have tried to stream on https://owncast.online/
but failed  becuase this is streaming url rtmp://192.168.8.103:1935/live please add this in publication list 
please please
im using restreamer from last 2 month i am happy but can you add this publication

**Comment by ioppermann** [comment]
Thanks for the suggestion. For now, you might try the generic RTMP publication.

**Comment by Restreamdev** [comment]
> Thanks for the suggestion. For now, you might try the generic RTMP publication.

ok sir thanks for quick reply

**Comment by jstabenow** [comment]
@Restreamdev
In v2.2.0, we have added an Owncast Publication Service. Please test this. 
Cheers

**Comment by Restreamdev** [comment]
Thanks You Very Much Sir

**Comment by kablin** [comment]
Now it doesnt work. Log from Owncast 


  | 10:26:39 AM 07/31/2025 | unable to write rtmp packet io: read/write on closed pipe

error | 10:26:39 AM 07/31/2025 | [out#0/hls @ 0x7b454fb4d7c0] Nothing was written into output file, because at least one of its streams received no packets.
error | 10:26:39 AM 07/31/2025 | [hls @ 0x7b454f8a4680] Variant stream info update failed with status ffffffea
error | 10:26:39 AM 07/31/2025 | [out#0/hls @ 0x7b454fb4d7c0] Could not write header (incorrect codec parameters ?): Invalid argument
error | 10:26:39 AM 07/31/2025 | Error while filtering: Invalid argument
error | 10:26:39 AM 07/31/2025 | [hls @ 0x7b454f8a4680] Unable to map stream at a:0
