### ISSUE TITLE
Can't use let's encrypt

### ISSUE THREAD

**Issue by Kdcius** [datarhei/restreamer#372]
Hello there.
I'm trying to access restreamer via https so I've configured the let's encrypt option in the restreamer admin page.
I've pointed it to my domain name and opened the needed ports in the host firewall.
I'm using port 8080 for https (accessed via 9020) and port 8181 for https (accessed via 443).
I can't figure out what is going wrong, I tried with other hosts and other clients nothing seems to work properly.
The host is running ubuntu and using the latest version of both docker and restreamer.
Tell me if there is any missing informations.
I'll be grateful for any support.
Thanks.

**Comment by ioppermann** [comment]
Do you see in the logs any error messages regarding Let's Encrypt? You'll find the logs in the settings with "Expert mode" enabled (see: https://docs.datarhei.com/restreamer/knowledge-base/manual/system-settings/logging).

**Comment by Kdcius** [comment]
Thanks for answering.
I've double checked in the logs and can't see anything about let's encrypt or https or anything related.
I tried to connect to the https port to see if any new line showed off but nothing.

**Comment by ioppermann** [comment]
Did you actually enable HTTPS according to our guide? https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-use-https-with-lets-encrypt

**Comment by Kdcius** [comment]
Yes It's turned on and configured as shown in the guide.

**Comment by Kdcius** [comment]
Any idea of what could have gone wrong ?

**Comment by jstabenow** [comment]
@Kdcius please describe exactly what you have configured. 
Including routing (Internet > Router > PC > Docker Port:Port).
Thanks.

**Comment by svenerbeck** [comment]
Hi @Kdcius 
We are closing your issue https://github.com/datarhei/restreamer/issues/372.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
//Sven
