### ISSUE TITLE
Help with HTTPS

### ISSUE THREAD

**Issue by iskconnairobi** [datarhei/restreamer#374]
Hi,

I'm trying to access restreamer via HTTPS but am unable to do so. My site uses Lets' Encrypt and port 443 is open. I can access the ui on port 8080 but 8181 is not working. Restreamer is running on Ubuntu 20.04

Kindly help.

The docs mention something about port forwarding but I don't know how to do that.

**Comment by svenerbeck** [comment]
Hi @iskconnairobi 

This doesn't sound like a problem with the Restreamer, but rather something to do with your network settings.

I advise you to find out how to release a public port in your network. You have to look into your router's manual like FritzBox, Zyxel, DrayTek, Cisco, D-Link, Netgear, or something like that.

If you send me the router model, I will look for the manual for port forwarding so that you can set that.

Then HTTPS should work if you have followed the instructions.

Here again is the link to the quick start video on YouTube: https://www.youtube.com/watch?v=uybznI9TGs0

Greetings
Sven

**Comment by iskconnairobi** [comment]
Hi Sven,

Thank you for your quick reply.

My Restramer is hosted on a Linode. I have no idea of the router used.

I tried binding 443 to 8181 but it gave an error messagestarting that the
port is used by other applications.

Port 8080 had no issues and just worked out of the box without any
additional configuration.

Please advice.

Thanks.

**Comment by svenerbeck** [comment]
Hi @iskconnairobi 

Please show me your Docker command to start the Restreamer.

Send me a screenshot of the HTTPS settings
![image](https://user-images.githubusercontent.com/12124066/175491634-c42e87fb-966b-4b4e-85b4-8583932c5ce6.png)

Thank you.

Greetings
Sven

**Comment by iskconnairobi** [comment]
![image](https://user-images.githubusercontent.com/108075003/175496180-7bcb4832-8607-464d-a400-f5d42bd4a382.png)

**Comment by iskconnairobi** [comment]
docker run -d --restart=always --name restreamer \
-v /opt/restreamer/config:/core/config \
-v /opt/restreamer/data:/core/data \
-p 8080:8080 -p 8181:8181 -p 1935:1935 \
datarhei/restreamer:latest

**Comment by svenerbeck** [comment]
Thank you. You have a rotator in the ports.

Please try this: 

```
docker run -d --restart=always --name restreamer 
-v /opt/restreamer/config:/core/config 
-v /opt/restreamer/data:/core/data 
-p 80:8080 -p 443:8181 -p 1935:1935 
datarhei/restreamer:latest
```

⚠️ **Remember**
From that on, the Restreamer is available via:

```
http://iskconnairobi.com/ui
https://iskconnairobi.com/ui
```

Greetings 
Sven

**Comment by iskconnairobi** [comment]
![image](https://user-images.githubusercontent.com/108075003/175504476-bfa83545-17ff-468c-978d-ee72f14bf618.png)

**Comment by iskconnairobi** [comment]
Both ports 80 and 443 have the same error

**Comment by iskconnairobi** [comment]
Currently, I have ProxyPass and so the playersite is loading when you visit iskconnnairobi.com

However, I want to embed the feed as this is not our final homepage

**Comment by svenerbeck** [comment]
Hi @iskconnairobi 
Thank you for the information. 

We don't understand your point because it works fine with HTTPS.

Try: 
[http://iskconnairobi.com/ui](http://iskconnairobi.com/ui)
[https://iskconnairobi.com/ui](https://iskconnairobi.com/ui)


_Or do you want to make the interface from the restreamer available internally?_


And here are your options with and without a proxy:

## Case 1
![case-1](https://user-images.githubusercontent.com/12124066/175539283-88f92fac-ea4a-4e09-97c9-a1fe969562bc.png)

```
docker run -d --restart=always --name restreamer 
-v /opt/restreamer/config:/core/config 
-v /opt/restreamer/data:/core/data 
-p 8080:8080 -p 1935:1935 
datarhei/restreamer:latest
```

## Case 2
![case-2](https://user-images.githubusercontent.com/12124066/175539391-298001be-757c-4a55-a4c6-8284744d6300.png)

1. Stop your proxy
2. Run:
```
docker run -d --restart=always --name restreamer 
-v /opt/restreamer/config:/core/config 
-v /opt/restreamer/data:/core/data 
-p 80:8080 -p 443:8080 -p 1935:1935 
datarhei/restreamer:latest
```

And enable Let's Encrypt

**Comment by iskconnairobi** [comment]
HI Sven,

Thank you for your assistance. 

I went with case 1 above as case 2 is still giving the same error as above where the bind-address is already in use.

I am still unable to embed the player due to a mixed content error. Kindly assist on this.

**Comment by svenerbeck** [comment]
Hey @iskconnairobi 
Thank you for waiting. Hope you had a nice weekend.

**Case 2:** Your Proxy uses the ports. That's why you need to stop the Proxy first. Afterward, the ports are free for the Restreamer.

Please describe 
>"I am still unable to embed the player due to a mixed content error. Kindly assist on this."

What are you trying? What does the embed code look like, and on which web page should it be inserted?

Cheerio
Sven

**Comment by iskconnairobi** [comment]
Hi Sven,

Thank you for your reply.

For Case 2, I can't stop the proxy because that's my web server as well. 

For the embedding:

I'm trying to insert the live feed on a WordPress page. Using the video block I have inserted the following URL - http://iskconnairobi.com:8080/d2922ef5-6dcc-4a4c-a1c2-a7eebb75c690.html

I've tried replacing HTTP with HTTPS but still doesn't work. However, clicking directly on the link above works although shows an unsecured connection.

Thanks.

**Comment by svenerbeck** [comment]
Hi @iskconnairobi 

We're on track after all! Use URL wit http**S** and **withou**t port. ;) 

Please use the URL:
https://iskconnairobi.com/d2922ef5-6dcc-4a4c-a1c2-a7eebb75c690.html


Cheerio
Sven

**Comment by svenerbeck** [comment]
Hi @iskconnairobi

Did it work?

Ticke will close soon

Greets
Sven

**Comment by iskconnairobi** [comment]
Hi Sven,

Thank you so much for your help thus far. 

Clicking on the link directly works. However, embedding it gives: 

![image](https://user-images.githubusercontent.com/108075003/176615315-c130c247-8041-4a09-aa70-82d590f09439.png)

**Comment by svenerbeck** [comment]
Hello iskconnairobi 

At this point, we can not continue with the support. We have now done everything for you. However, it has become clear that you lack much basic knowledge. 

We stop with the free support we carry out here with our team. There will always be more questions because of your incomplete knowledge of HTML. It makes no sense anymore because we have answered all questions.

You have entirely different problems if you cannot embed an iFrame in an HTML page. 

Here is a tutorial for it. [https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-display-a-live-stream-on-my-website](https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-can-i-display-a-live-stream-on-my-website)

**You have two possibilities now.**

1. Get someone on your side who is experienced in web technology. 
2. You can become a Patron, and then we will help you in the exclusive Discord. As a Patron, you get access to Discord and direct chat to our exclusive support area. Tier 1 we would recommend. [https://www.patreon.com/datarhei](https://www.patreon.com/datarhei)

No misunderstanding. We won't get anywhere like this. 

Greetings
Sven

**Comment by threehappypenguins** [comment]
> Hi,
> 
> I'm trying to access restreamer via HTTPS but am unable to do so. My site uses Lets' Encrypt and port 443 is open. I can access the ui on port 8080 but 8181 is not working. Restreamer is running on Ubuntu 20.04
> 
> Kindly help.
> 
> The docs mention something about port forwarding but I don't know how to do that.

I noticed that you got this all working, and on your site, it redirects http to https. How did you get it to redirect? I cannot figure this out.

**Comment by syadnom** [comment]
I'm having the same issue.  ports 8080 and 8181 open to internet, docker proxy has 8080>8080 and 8181>8181 into the container.  8080 works, 8181 doesn't.  letsencrypt is enabled and set as 8181
