### ISSUE TITLE
Extend history time of the VideoPlayer for Streaming

### ISSUE THREAD

**Issue by giuseppegambino92** [datarhei/restreamer#382]
Hi everyone, how can I extend the Player history of a Streaming Video. From what I can see I can only go back 1 minute and 50 seconds (approx.). I would like to extend it to a few hours, what can I do?

**Comment by svenerbeck** [comment]
Hi @giuseppegambino92 

Here you can see how to activate DVR. If you have enough RAM and turn up the time you will have more rewind in the video. Take a look at this : https://www.youtube.com/watch?v=7MLVp0alTtA&t

Cheerio
Sven

**Comment by jstabenow** [comment]
Hey @giuseppegambino92 
All questions resolved?

**Comment by svenerbeck** [comment]
Hi @giuseppegambino92 
We are closing your issue https://github.com/datarhei/restreamer/issues/382.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
//Sven
