### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by bitfreak030** [datarhei/restreamer#384]
Is there a method or possibility to make playlists with video's?
Would be nice to play video's from those google searches like "intitle index.of mp4 anime"
with a option to play video's in order or random. Tnxs for making this program.

**Comment by svenerbeck** [comment]
Hello 
A beautiful idea. That is not possible right now.
Cheerio
Sven

**Comment by bitfreak030** [comment]
tnxs for adding this  (allow relative URLs in content in static routes) in v2.2.0  
Its allowed to stream anime on Twitch.
With a nice playlist, whe can stream 24/7 then. 
Will add a logo of datarhei/restreamer  and support you. ;)  Ty.

**Comment by Urbanshenkie** [comment]
Found one problem. When playing a relative url (Works great) 
going in a menu will give this error when you switch back to ui  
"The media could not be loaded, either because the server or network failed or because the format is not supported"
video is still streaming then. Only not showing anymore in UI.  ;)

**Comment by bitfreak030** [comment]
Oh ja. Can't add a logo when streaming it without publish it to website.

**Comment by svenerbeck** [comment]
Hello 

We are closing your ticket https://github.com/datarhei/restreamer/issues/384.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
