### ISSUE TITLE
Raspivid commands not working

### ISSUE THREAD

**Issue by poopyface0931** [datarhei/restreamer#393]
When I attempt to run raspivid commands (-ev, -rot etc) I receive the following mmal errors:

mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

From what I've been able to gather, this is related to the Bullseye legacy workaround/hack. The latest Restreamer rotate feature is not working either, presumably for the same reason. I considered returning to Buster, but it runs hotter as CPU usage is less efficient on 4B, averaging around 50% for H264 encoding/streaming (with 1800Mhz unlocked), as compared to Bullseye's 35% average. 

Is there a way to re-implement raspivid support? Or is libcamera support on the horizon?

**Comment by ioppermann** [comment]
On the latest releases of Raspbian, raspivid is not anymore supported. They will go all-in with libcamera. Please read the official documentation for the camera on https://www.raspberrypi.com/documentation/accessories/camera.html or check our guide: https://docs.datarhei.com/restreamer/knowledge-base/user-guides/how-do-i-stream-a-raspicam#enabling-pi-camera

**Comment by svenerbeck** [comment]
Dear @poopyface0931 
We are closing your issue #393.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
