### ISSUE TITLE
A way to stream multiple cameras to Telegram

### ISSUE THREAD

**Issue by yayitazale** [datarhei/restreamer#395]
Hi:

I'm want to create a channel with a 24/7 stream with multiple cameras. Telegram only allows 1 stream so is there any way to change the config of restreamer via API to change the origin of the camera, or change witch camera is publishing to telegram?

If there is a way, I can use a telegram bot in the channel with inline buttons to allow the user to select the camera they want.

Thanks.

**Comment by jstabenow** [comment]
Hey @yayitazale. Look here:
- [CrashOv62](https://github.com/CrashOv62): To present 2 or more video sources in 1 video output (Mixer) https://github.com/datarhei/restreamer/discussions/345#discussioncomment-2939507

And it won't work without an API 👍 , but there is still a lot to do. 
So it will take time.

**Comment by yayitazale** [comment]
Thanks a lot!

**Comment by svenerbeck** [comment]
Dear @yayitazale 
We are closing your issue #395.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
