### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by Pimmetje** [datarhei/restreamer#397]
For my current setup there are probems with freeing memory. 

I have a system with 10Gigabyte allocated to the docker image. I have 5 active streams on the system. All of them using DVR to disk. 

The memory still keeps on growing. And the performance of streaming is poor as a result. 
I would love to use it in a way that the last 15 minutes can be stored in memory while the rest is read from disk when needed. 

But currently there seem to be a issue with memory usage. I have seen similar effect even before the DVR was added.

**Comment by ioppermann** [comment]
In the config.json you can set value of `debug.force_gc` to `15`. This will run the garbage collector every 15 seconds. Go is quite greedy when it comes to memory. With this setting the memory will be freed earlier.

**Comment by svenerbeck** [comment]
Dear @Pimmetje 
We are closing your issue #397.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
