### ISSUE TITLE
I can`t input stream key in custom RTMP

### ISSUE THREAD

**Issue by WhiteBite** [datarhei/restreamer#400]
I try to connect with Trovo. I have  Stream URL and Stream key. But in custom RTMP i can`t input key

**Comment by ioppermann** [comment]
You can add the stream key directly to the streaming URL: rtmp://livepush.trovo.live/live/[your trovo stream key]

**Comment by WhiteBite** [comment]
ty

**Comment by svenerbeck** [comment]
Please update to the latest version, and you will find Trovo as a publication service.

**Comment by svenerbeck** [comment]
Hi @WhiteBite 
We are closing your issue https://github.com/datarhei/restreamer/issues/400.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
//Sven
