### ISSUE TITLE
Feature Request: combined chat

### ISSUE THREAD

**Issue by Fred-DTV** [datarhei/restreamer#402]
Hi again,

An amazing addition to restreamer would be to have a combined chat tool, when streaming to multiple different platforms.
This idea is obviously stolen from restreamer.io, which we used before, however the amazing @steveseguin has already done a great job building something the works alike: https://github.com/steveseguin/social_stream

Maybe it would be possible to integrate Steve's work with restreamer?

**Comment by svenerbeck** [comment]
Hi DachsbauTV

This is a lot of work and will not be implemented quickly without sponsorship of the function or help from an external software developer. Maybe there will be one day. We've added it to the [feature list](https://github.com/datarhei/restreamer/discussions/345#discussion-4108562).

Cheerio
Sven

**Comment by svenerbeck** [comment]
Dear @DachsbauTV  
We are closing your issue #402.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
