### ISSUE TITLE
Starting/Stopping Live Streams using YouTube/Facebook APIs

### ISSUE THREAD

**Issue by damanjit-singh** [datarhei/restreamer#405]
It would be great if it is possible to start YouTube and Facebook livestreams from restreamer itself. Currently, one needs to send feed to restreamer and then from YouTube studio and Facebook Live press the "**Go Live**" button. But in SaaS products like Restream.io and Castr, the user can directly "Go Live" from Restream.io/Castr dashboards. It would be great if this can be implemented in Restreamer. Is this planned or already suggested?

**Comment by svenerbeck** [comment]
Hi @damanjit-singh
thank you for your message.

This is already a feature request. Please take a look at: [https://github.com/datarhei/restreamer/discussions/345#discussion-4108562](url)

Cheerio 
Sven

**Comment by adriel** [comment]
IDK what happened to that link but when clicked it goes to `https://github.com/datarhei/restreamer/issues/url`
Full link: [https://github.com/datarhei/restreamer/discussions/345#discussion-4108562](https://github.com/datarhei/restreamer/discussions/345#discussion-4108562)

**Comment by gregc815** [comment]
Is there an update on this? 
As you know, the restreaming companies have an access token to get the one-time stream key to auto-start the live stream which is what I'd like to do instead of having to log into Facebook Live Producer and click a button each time. 

If this feature request is not ready yet, is there a way to write the stream key into the Restreamer Facebook plugin or command line arguments to connect to Facebook or YouTube stream key parameters? 

Essentially, writing the stream key into this field using an outside process as described above. 
![image](https://github.com/datarhei/restreamer/assets/987575/f40d4736-332b-4637-a80d-0dfb7fd4cac7)

**Comment by KopiasCsaba** [comment]
> Is there an update on this? As you know, the restreaming companies have an access token to get the one-time stream key to auto-start the live stream which is what I'd like to do instead of having to log into Facebook Live Producer and click a button each time.
> 
> If this feature request is not ready yet, is there a way to write the stream key into the Restreamer Facebook plugin or command line arguments to connect to Facebook or YouTube stream key parameters?
> 
> Essentially, writing the stream key into this field using an outside process as described above. ![image](https://user-images.githubusercontent.com/987575/248601739-f40d4736-332b-4637-a80d-0dfb7fd4cac7.png)

Can you send a link on what is this exactly? Is this suggesting, that without any special api keys, registered fb apps, it is possible to start a live stream if you have the stream key padded with parameters?! Couldn't find info on it. Thanks!

**Comment by FilipStadler** [comment]
If you setup facebook and youtube to use a permanent static key - this will solve part of your problem.
On Youtube you can add information about the livestream up front - but facebook needs more information before it goes live and thats stupid - I even have to fake acces to the live producer via a "desktop" mode on the browser because they have som limits on streams from mobile devices where a uknown number of users is needed. 
So its alot more easy to embed the player on a website and share the link ;)  maybe even use peertube and avoid the bigtech problems.

**Comment by gregc815** [comment]
I messaged Sven (leader of the Resteamer project) a while back as I saw the feature request was closed.  He told me he did not close it so the person who initially requested it must have. 

For the screenshot I shared, I can log into Facebook's API and get a one time token that I can paste into Restreamer and it will auto start the live stream (no need to go into Facebook Live Producer to start it) - but only once as the Facebook token expires in one hour and after one use.  

So a program to go to Facebook, get the token and write it into the Restreamer Stream Key field needs to be created.  

Sven had sent me a link showing the documentation one could use to create the program.  https://docs.datarhei.com/core/guides/rtmp
