### ISSUE TITLE
adavenced stats   label:feature 

### ISSUE THREAD

**Issue by kalashnikov2** [datarhei/restreamer#408]
Hello

 I would like the restreamer to have more detailed statistics

I don't know if this code is easy to incorporate
https://github.com/faryon93/hlswatch
"hlswatch is a simple program to keep track of the concurrent viewer count of a HLS live stream."

Thank you

**Comment by svenerbeck** [comment]
Hello [kalashnikov2](https://github.com/kalashnikov2)
thank you for your message.
It is on the roadmap.
Cheerio
Sven

**Comment by svenerbeck** [comment]
Hello 

We are closing your ticket https://github.com/datarhei/restreamer/issues/408.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
