### ISSUE TITLE
AV1 Dash transcoding fails - Update FFMPEG?

### ISSUE THREAD

**Issue by DatCaptainHorse** [datarhei/restreamer#415]
Heyo! Been testing this as a docker on my server, it's a cool project!

Issue I've hit is that transcoding AV1 encoded DASH is not possible and errors out.
However, from local testing FFMPEG 5.x seems to transcode without issues, so would it be possible to upgrade Restreamer to use 5.x version of FFMPEG? Or atleast provide a "custom FFMPEG location" variable that it will use instead?

Here's the error segment just in case:
```
Error while decoding stream #0:0: Invalid argument
[av1       ] video_get_buffer: image parameters invalid
[av1       ] get_buffer() failed
[av1       ] thread_get_buffer() failed
[av1       ] Failed to allocate space for current frame.
[av1       ] Get current frame error
Error while decoding stream #0:0: Invalid argument
[av1       ] Failed to get reference frame.
Error while decoding stream #0:0: Invalid argument
Cannot determine format of input stream 0:0 after EOF
```

Edit: I tried to set the `CORE_FFMPEG_BINARY` however it wouldn't work, kept saying the custom ffmpeg didn't exist.

**Comment by svenerbeck** [comment]
Hi @DatCaptainHorse 
Fair point. We will upgrade to FFMpeg 5x in the next update or two. Sorry that it is not done yet. There is much work going on in the project right now. There are only 3 of us. 

Cheerio
Sven

**Comment by svenerbeck** [comment]
Hi @DatCaptainHorse 
Small sign of life from datarhei. Good news, we have FFmpeg 5.0 enabled in 2.4.x and are thus approaching AV1. Could work in the next version.

Greetings
Sven

**Comment by svenerbeck** [comment]
Hello 

We are closing your ticket https://github.com/datarhei/restreamer/issues/415.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
