### ISSUE TITLE
RTSP over TCP

### ISSUE THREAD

**Issue by strarsis** [datarhei/restreamer#42]
What exactly does the "RTSP over TCP" option change? 
What is used instead of TCP when this option is not checked, UDP? 
Should this option also be enabled except in case of troubleshooting/workaround for specific issues?

**Comment by jstabenow** [comment]
Yes, if your Source/Camera supports only RTSP over TCP, you can enable this option to speed up process initialization because UDP is not tested. And the most of our tested cameras support TCP only or UDP was problematic.

This option inserts "-rtsp_transport tcp". See also:
https://ffmpeg.org/ffmpeg-all.html#rtsp  > rtsp_transport

**Comment by strarsis** [comment]
@jstabenow: Thanks for your answer!
Is this project active at the moment?
I would love to see [PTZ patrol support](https://github.com/datarhei/restreamer/issues/40) for ONVIF in restreamer or similar helper software.

**Comment by svenerbeck** [comment]
Hello strarsis
nice case. 
We're revitalizing the project right now and in the next weeks. 
Cheerio
Sven

**Comment by strarsis** [comment]
@svenerbeck: This is great! A simple PTZ programming GUI would be a nice addition to restreamer.
