### ISSUE TITLE
RPI3 Framebuffer very slow and no audio  restreamer-v2.3.0

### ISSUE THREAD

**Issue by FilipStadler** [datarhei/restreamer#420]
If I play cvlc of the hls stream localy linke this 

cvlc http://localhost:8080/memfs/894d4999-9530-40c6-be3c-38322eb23516.m3u8

it works fine on the rpi3 but using framebuffer is not working.

Another thing is when I tried to deaktivate the rtmp out server  is making it aktive when i press save.

**Comment by jstabenow** [comment]
Hey @FilipStadler :-)
The checkbox remains active only if the video source is an RTMP ingest stream. Otherwise, it should be unselectable.

However, there is an error if you have an RTMP ingest stream and want to output SRT. 
I will fix this.

Regarding your request:
Please show the [report](https://docs.datarhei.com/restreamer/knowledge-base/manual/process-report) of the main and framebuffer (publication service) process.
Then we will look further.

**Comment by FilipStadler** [comment]
I tried on a raspberrypi 4 and it was working fine.

**Comment by svenerbeck** [comment]
Dear @FilipStadler 
We are closing your issue #420.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
