### ISSUE TITLE
There was an error connecting to Restreamer Core at https://

### ISSUE THREAD

**Issue by therealmrnerd** [datarhei/restreamer#421]
Trying to proxy with Nginx and hitting this "There was an error connecting to Restreamer Core at https://" error. I've tried proxying to the localhost and the docker's IP, with docker's TLS on and off and with TLS on the proxy on and off but still the same. Any suggestions?

Nginx Config except server and TLS details

       location ~* /restreamer/ {
 
            rewrite ^/restreamer/(.*) /$1 break;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_pass http://172.17.0.2:3876;
            proxy_redirect off;

Also, why is a H265 stream not found on RTMP from OBS?

![Screenshot 2022-10-01 071227](https://user-images.githubusercontent.com/55374174/193395515-8675e411-ca8e-4038-b2e1-9d3c2c99bc2f.jpg)

**Comment by jstabenow** [comment]
Hey @therealmrnerd 

1. UI Access (https://docs.datarhei.com/restreamer/knowledge-base/user-guides/proxying):
```sh
Interface URL: 
http://[nginx-address]/restreamer/ui/?address=http://[nginx-address]/restreamer/
```

2. HEVC is not supported by RTMP. That's why it doesn't work. Please use H.264.

**Comment by svenerbeck** [comment]
Hi @therealmrnerd 
We are closing your issue https://github.com/datarhei/restreamer/issues/421.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team

**Comment by HeliosLHC** [comment]
> Hey @therealmrnerd
> 
> 1. UI Access (https://docs.datarhei.com/restreamer/knowledge-base/user-guides/proxying):
> 
> ```shell
> Interface URL: 
> http://[nginx-address]/restreamer/ui/?address=http://[nginx-address]/restreamer/
> ```
> 
> 2. HEVC is not supported by RTMP. That's why it doesn't work. Please use H.264.

Hi, I have a similar issue but on the player site (not the admin /ui route) where the page tries to still read from /memfs route instead of using the "address" query parameter to calculate the new "memfs" path. Would you be aware of any setting or option that would enable changing the external path used to locate the memfs directory?
