### ISSUE TITLE
Adding channel without active source

### ISSUE THREAD

**Issue by szergej01** [datarhei/restreamer#422]
Hi,

Is it possible to make channels without active source for future streaming? If not, it will be a good future update for us! 💯 

![image](https://user-images.githubusercontent.com/28932799/193484356-223fd791-2122-48f8-8585-6b42bd811ded.png)

**Comment by noho501** [comment]
Agree

**Comment by saschafoerster** [comment]
I had the same issue. Now I need to open OBS, copy the RTMP-address, start streaming, and only then I can proceed to create new destinations. Would be great if I can create a channel and destinations without needing to start OBS, as in our situation this are two different tasks done by different people.

**Comment by ioppermann** [comment]
From the wizard you can change to the "Advanced Setup". There you'll have the possibility to create a virtual source in order to create the channel. Whenever the actual source is ready you can change from the virtual source to the RTMP source.

**Comment by saschafoerster** [comment]
Of course this is a workaround in the best meaning of the word. It is work and it is "around". And a painful one. I had to make 9 more clicks and decide which of the (irrelevant) options are the right one by creating a virtual stream, just for the simple task of creating a RTMP stream, which is a clear and easy option at the start, which I can't complete, when I don't send anything. I wish there was just a little warning (hey, there is no signal yet, would you still like to continue, yes), done. :)

**Comment by svenerbeck** [comment]
Added it as a feature Request https://github.com/datarhei/restreamer/discussions/345

If someone here has pressure on the function, he may contact us. There are certainly ways to speed up the development!

Thank you for your understanding.

Cheerio
Sven

**Comment by FilipStadler** [comment]
It would be  very nice to have chanals that are not/never shown in the player site list because it can be virtual source or other input streams that can stream to the visible included playersite list.
 - like an option if input included in the player site list or not. 
 
Non visible input streams can be used to push the stream for a visible chanal and it would allow to add sources that mainly are to allow publishing.   A workaroud solution is maybe to run two restreamers where one is only for the secret chanals without a player Playersite active (it can be turned to non active) but selection if a chanal/stream is included in the playersite list would be the same :)   I am a really not a programmer so it better I just share ideas and not make some bad ugly code with alot of bugs but I really like the design on the restreamer webgui.

**Comment by jstabenow** [comment]
> It would be very nice to have chanals that are not/never shown in the player site list because it can be virtual source or other input streams that can stream to the visible included playersite list.
> 
> * like an option if input included in the player site list or not.
> 
> Non visible input streams can be used to push the stream for a visible chanal and it would allow to add sources that mainly are to allow publishing. A workaroud solution is maybe to run two restreamers where one is only for the secret chanals without a player Playersite active (it can be turned to non active) but selection if a chanal/stream is included in the playersite list would be the same :) I am a really not a programmer so it better I just share ideas and not make some bad ugly code with alot of bugs but I really like the design on the restreamer webgui.

Good idea @FilipStadler! Let's put it on the roadmap 👍

**Comment by svenerbeck** [comment]
Hello @szergej01 

We are closing your ticket https://github.com/datarhei/restreamer/issues/422.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
