### ISSUE TITLE
How to import a Backup from the configuration/db  with docker-compose?

### ISSUE THREAD

**Issue by xmochx** [datarhei/restreamer#427]
**Subject of the issue**
I would like to use a backup of the configuration to use it on a new server
**Your environment**
Ubuntu/Docker-Composer 
I use volumes and have all the data for db/config/data.

**Steps to reproduce**
After starting restreamer it does not use the db and shows me:

restreamer      | ts=2022-10-15T09:15:35Z level=INFO component="Import" msg="D**atabase doesn't exist and nothing will be imported**" database="/core/config/v1.json" version="v1"

Any idea how to use the saved backup from the volumes in the startup of restreamer?

Than you

**Comment by svenerbeck** [comment]
Hi @xmochx 
There is a second folder if you mounted it with the old system.
opt/restreamer/data and opt/restreamer/config

Cheerio 
Sven

**Comment by svenerbeck** [comment]
Hi @xmochx 
We are closing your issue https://github.com/datarhei/restreamer/issues/427.

This may be due to the following reasons:

- Problem/inquiry has been solved
- The ticket remained unanswered by you for a more extended time
- The problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please do not open related tickets twice. Always answer/ask in the original issue with the same problem.

Your datarhei team
Sven
