### ISSUE TITLE
Virtual input: looping image or video with audio stream muxed in

### ISSUE THREAD

**Issue by riddlenl** [datarhei/restreamer#432]
I think it would be a nice idea to have the ability to create 3 new virtual inputs:

* Live video stream and mix a separate live audio stream
* Loop a (local) video file and mix a live audio stream in
* Loop an array of images (or just one) and mix a live audio stream

**Comment by jstabenow** [comment]
> I think it would be a nice idea to have the ability to create 3 new virtual inputs:
> 
> * Live video stream and mix a separate live audio stream

Muxing video and audio streams already works. Just switch to the advanced wizard.

> * Loop a (local) video file and mix a live audio stream in
> * Loop an array of images (or just one) and mix a live audio stream

Great ideas and already on the roadmap 👍

**Comment by riddlenl** [comment]
I'm trying to mux a live stream (receive rtmp) with an icecast mp3 stream (remote).

Probing both separately works and they see the stream. However, the video stream loads, but there's no audio. There is an audio channel streamed according to the process logs/details.

Stream #0:0: Video: h264 (Constrained Baseline), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], q=2-31, 1500 kb/s, 30 fps, 30 tbr, 90k tbn, 30 tbc
  Stream #0:1: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s

**Comment by ioppermann** [comment]
Try to convert the audio to AAC.

**Comment by svenerbeck** [comment]
Dear @riddlenl 
We are closing your issue #432.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
