### ISSUE TITLE
SRT/OBS Issue

### ISSUE THREAD

**Issue by shortcast20** [datarhei/restreamer#446]
Hi,

At first, I am a streamer on Twitch and I would like to make IRL streams by using SRT Protocol.
My broadcast software that I'm using is OBS Studio.

When I installed restreamer on my computer, I did the steps like the documentations. But it seems to not working correctly with SRT.
With the RTMP, it is working correctly, as long as I put srt://192.168.X.X:6000 in my OBS.... as shown in the video http://www.youtube.com/watch?v=ATG2bOujuPU nothing wants to start after pression "start streaming".

![image](https://user-images.githubusercontent.com/117627965/200247200-3d1175bf-1fc3-4dc0-ae64-0b1bb55a060e.png)

And, I also unlocked ports 6000 to 6007.

Please help !

**Comment by svenerbeck** [comment]
We only process tickets with error logs. It is necessary, especially in your case, to see the error. Here you can see how to get the logfile: https://www.youtube.com/watch?v=mZMGrweFCsM — Thank you for being so understanding.

**Comment by shortcast20** [comment]
Unfortunately, I am not able to get the report...

**Comment by svenerbeck** [comment]
Unfortunately, we can not help you without the report.

**Comment by svenerbeck** [comment]
Please take a look at Discord PM.

**Comment by svenerbeck** [comment]
Hey Ho @shortcast20 
Thank you for the log file in Discord. The file shows that no SRT data arrives at the Restreamer. The firewall can cause such an error on Windows. You should check it. Just disable it and see if it works.

Cheerio
Sven

**Comment by svenerbeck** [comment]
Dear @shortcast20 
We are closing your issue #446.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
