### ISSUE TITLE
Stream pausing

### ISSUE THREAD

**Issue by badincite** [datarhei/restreamer#453]
Attempting to get a m3u8 stream to pause and resume where paused from. As it is right now after resuming from pause it just jumps to the live stream. I also tried adjusting some of the caching settings to see if that would allow for pausing with no luck. The manual documentation doesn't appear to be there yet for this expert mode setting.

Running in docker and just upgraded to the newest 2.4.0

**Comment by svenerbeck** [comment]
Hello @badincite 

No data is stored by default. That's why the video data for playback is missing. First, you have to activate the [DVR](https://www.youtube.com/watch?v=7MLVp0alTtA). Then DVR function will save the stream in the background. If you then restart, it goes on in the optima case.

Cheerio
Sven

**Comment by badincite** [comment]
> Hello @badincite
> 
> No data is stored by default. That's why the video data for playback is missing. First, you have to activate the [DVR](https://www.youtube.com/watch?v=7MLVp0alTtA). Then DVR function will save the stream in the background. If you then restart, it goes on in the optima case.
> 
> Cheerio Sven

Awesome!

**Comment by svenerbeck** [comment]
Dear @badincite 
We are closing your issue #453.

This may be due to the following reasons:

- **Problem/inquiry has been solved**
- Ticket remained unanswered by you for a longer period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

💛 If you were satisfied with the support and we could help you, please **[rate us on Google](https://g.page/r/CSv68cfIr9l9EBE/review)**. 

With kind regards,
Your datarhei team
