### ISSUE TITLE
RTMP IP camera stream error after restart restreamer service

### ISSUE THREAD

**Issue by specuniu** [datarhei/restreamer#454]
I have ongoing RTMP stream from IP camera. After restart Restreamer service RTMP stream from restreamer can't start. After double check all settings I have found solution - I have to stop RTMP from camera and after Start it again. Could you double check it in restreamer code?

"Error: rtmp://localhost/xyz.stream: I/O error"

**Comment by jstabenow** [comment]
1. Restreamer version?
2. Please attach the process report

**Comment by jstabenow** [comment]
Hello @specuniu 

We are closing your ticket.

This may be due to the following reasons:
- Problem has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

With kind regards,
Your datarhei team
Jan
