### ISSUE TITLE
How to add simple authorization for Playersite

### ISSUE THREAD

**Issue by goblinmaks** [datarhei/restreamer#469]
How to add simple authorization for playersite if it possible ? 
Thanks,

**Comment by svenerbeck** [comment]
Hi @goblinmaks 

HTAccess does not exist right now. You could solve this just using NGINX with proxy forwards and keeping the Restreamer sites separately.

Cheerio
Sven

**Comment by privatesam** [comment]
I use nginx as a proxy and manage the user logins there but it would be great if Restreamer had its own user management system so that we could track stats per user.

**Comment by svenerbeck** [comment]
> I use nginx as a proxy and manage the user logins there but it would be great if Restreamer had its own user management system so that we could track stats per user.

@privatesam There is already a feature request for this. Follow the thread to get the update.  https://github.com/datarhei/restreamer/discussions/345

**Comment by svenerbeck** [comment]
Hello @goblinmaks 

We are closing your ticket https://github.com/datarhei/restreamer/issues/469.

This may be due to the following reasons:

- Problem/inquiry has been solved
- **Ticket remained unanswered by you for a more extended period**
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
