### ISSUE TITLE
API

### ISSUE THREAD

**Issue by msikorski26** [datarhei/restreamer#479]
I have generated myself an api key, I go into swagger ui to check the operation. And every time it throws me out that I supposedly have a bad token
![image](https://user-images.githubusercontent.com/41286754/204133227-16e43fcc-3d94-494d-af64-7e4073efc3f1.png)

**Comment by ioppermann** [comment]
In the authorization field in the UI you have to write "Bearer [access key]".

**Comment by svenerbeck** [comment]
Hello @mscodepl 

We are closing your ticket https://github.com/datarhei/restreamer/issues/479.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue.
