### ISSUE TITLE
Possible to pubblish this to a google drive? Maybe using rclone?

### ISSUE THREAD

**Issue by amgno** [datarhei/restreamer#484]
^^
 Pls? 👉 👈

**Comment by svenerbeck** [comment]
What does that mean?

**Comment by svenerbeck** [comment]
Hello @heryoff 

We are closing your ticket https://github.com/datarhei/restreamer/issues/484.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

**Comment by amgno** [comment]
Sorry for the late response, what I'm actually asking for is if there is any method to upload the recording (wich I saw restream can't actually perform on it's own) to a cloud service such as google drive. If there is none do you suggest anything?

I currenctly have a custom docker image with nginx rtmp module and an rclone mount, the only problems that I have with that is:
1. I would love to replace it with restream because I find it more easier to manage and better looking in general
2. My rtmp stream get cut every 30m and encoded to mp4 and then uploaded to drive, what I would like is a way to direct uploading without waiting for the .mp4 to finish encoding so that I can disable the 30m cut and keep making the file bigger.

Sorry If I'm not that clear, English is not my main language.

Thanks in advance
