### ISSUE TITLE
a way to upload let's encrypt keys received from dns challenge

### ISSUE THREAD

**Issue by e2950** [datarhei/restreamer#488]
can't figure out how to get the built in lets encrypt working. maybe a blocked port and i can't control the ports but i can do the dns challenge and have the key but no way to install them in. thank you for any help.

**Comment by svenerbeck** [comment]
We only process tickets with error logs. Here you can see how to get the logfile: https://www.youtube.com/watch?v=mZMGrweFCsM — Thank you for being so understanding.

**Comment by e2950** [comment]
> We only process tickets with error logs. Here you can see how to get the logfile: https://www.youtube.com/watch?v=mZMGrweFCsM — Thank you for being so understanding.

[reportLarix.txt](https://github.com/datarhei/restreamer/files/10298356/reportLarix.txt)

**Comment by chepehj** [comment]
hola

**Comment by ioppermann** [comment]
Depending on your certificate manager, you should find two files: `fullchain.pem` and `privkey.pem` on the system where you ran the challenge, e.g.

```
/etc/letsencrypt/live/example.com/fullchain.pem
/etc/letsencrypt/live/example.com/privkey.pem
```

Add the paths to your Restreamer `config.json`, e.g.

```json
{
   "tls": {
      "address": ":8081",
      "enable": true,
      "auto": false,
      "cert_file": "/etc/letsencrypt/live/example.com/fullchain.pem",
      "key_file": "/etc/letsencrypt/live/example.com/privkey.pem"
   },
}
```

Later, when you renew the certifiactes you have to restart Restreamer in oder to reload the renewed certificates.

**Comment by svenerbeck** [comment]
Hello @e2950 

We are closing your ticket https://github.com/datarhei/restreamer/issues/488.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
