### ISSUE TITLE
Generate a token per channel

### ISSUE THREAD

**Issue by pablotdv** [datarhei/restreamer#495]
### Discussed in https://github.com/datarhei/restreamer/discussions/490

<div type='discussions-op-text'>

<sup>Originally posted by **pablotdv** December 30, 2022</sup>
Is there a way to generate a token per channel?

Because the id generated to configure the stream platform is the same to use in the player.

My concern is about security as if someone knows a little more about the restreamer platform they can use the id to stream to a channel that belongs to another user.

So I would like to protect the stream URL with a token, but I want to generate a different token per channel.</div>

**Comment by svenerbeck** [comment]
Hello @pablotdv 

We are closing your ticket https://github.com/datarhei/restreamer/issues/495.

This may be due to the following reasons:

- Problem was explained and handled in another ticket or discussion.
- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period

You can reopen this ticket at any time!

Please only open related tickets or discussions once! Always answer/ask in the original ticket with the same issue!
