### ISSUE TITLE
what is "RTMP app for publishing."

### ISSUE THREAD

**Issue by codefist** [datarhei/restreamer#496]
I can't figure out what this means.  There's zero documentation.

**Comment by ioppermann** [comment]
The RTMP application name is a path prefix for the stream name for publishing and playback. This is sometimes required by RTMP clients. It can be an arbitrary name (e.g.` /foobar`) and will be prefixed to the stream name (e.g. `/foobar/live.stream`).

**Comment by svenerbeck** [comment]
Hello @codefist 

We are closing your ticket https://github.com/datarhei/restreamer/issues/496.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
