### ISSUE TITLE
Still Image - Connection Lost

### ISSUE THREAD

**Issue by ragman-mw** [datarhei/restreamer#511]
Hi together,

is it possible to use a still image from the last running state of a webcam if the connection get lost. Or should i change the connection timeout to e.g. 1 hour?

Thx for your help.

**Comment by ioppermann** [comment]
@ragman-mw

> is it possible to use a still image from the last running state of a webcam if the connection get lost.

This is currently not possible

**Comment by svenerbeck** [comment]
Hello @ragman-mw 

We are closing your ticket https://github.com/datarhei/restreamer/issues/511.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
