### ISSUE TITLE
Install on Nvidia Jetson Nano (docker: Error response)

### ISSUE THREAD

**Issue by VladimirVecera** [datarhei/restreamer#521]
I can't install Restreamer on my Nvidia Jetson nano. To install on more I have to use sudo, otherwise docker says I don't have rights.
`sudo docker run -d --restart=always --name restreamer -p 8080:8080 -e "RS_USERNAME=admin" -e "RS_PASSWORD=pass" --privileged datarhei/restreamer:latest`

And this is error code:

> vecerapl@nvidia-streamer:~$ sudo docker run -d --restart=always --name restreamer -p 8080:8080 -e "RS_USERNAME=admin" -e "RS_PASSWORD=slunce" --privileged datarhei/restreamer:latest
Unable to find image 'datarhei/restreamer:latest' locally
latest: Pulling from datarhei/restreamer
6875df1f5354: Already exists
56e8921bdcb0: Pull complete
6ef9b267ba63: Pull complete
cb0ad799df19: Pull complete
4f4fb700ef54: Pull complete
f771dccca771: Pull complete
ae444fb778ee: Pull complete
28366820ee16: Pull complete
28ef8672e1d6: Pull complete
62e9006e5ae9: Pull complete
Digest: sha256:cb7cb66d380e756f8c519359b495ef1632390f796eb74fd4bf201e7bcd7d66a6
Status: Downloaded newer image for datarhei/restreamer:latest
98bb62e88f6b974a82206f51b1887c66c4a26a70fa8633ef962e717e669f281e
docker: Error response from daemon: failed to create endpoint restreamer on network bridge: failed to add the host (veth19f4fe4) <=> sandbox (veth81f8992) pair interfaces: operation not supported.

> vecerapl@nvidia-streamer:~$ sudo docker ps -a
CONTAINER ID   IMAGE                        COMMAND              CREATED         STATUS    PORTS     NAMES
98bb62e88f6b   datarhei/restreamer:latest   "/core/bin/run.sh"   5 minutes ago   Created             restreamer

**Comment by svenerbeck** [comment]
Hello Vladimir

I appreciate your question. To install Restreamer on your Nvidia Jetson Nano, you must use the "sudo" command. This is necessary because Restreamer must access specific devices that regular users cannot.

By using "sudo," you will temporarily become a superuser with all the necessary permissions and access rights to perform the installation of Restreamer. You might need to use "sudo to perform the installation or access the required devices.

We hope this information is helpful to you. Please don't hesitate to contact us if you have any further questions.

Cheerio
Sven
