### ISSUE TITLE
HDR 10bit support HVEC H265

### ISSUE THREAD

**Issue by roulendz** [datarhei/restreamer#552]
**Is your feature request related to a problem? Please describe.**
Currently, when sending a 10-bit signal from OBS through the SRT input, it needs to be re-encoded to H264, which does not support 10-bit HDR. YouTube has been supporting HDR streaming for some time now, as shown here: [HDR 10bit support HEVC H265](https://support.google.com/youtube/answer/10265272).
I believe this would significantly benefit new creators looking to distinguish themselves with HDR live streams, particularly those who have HDR-supporting devices.

**Describe the solution you'd like**
If implementing H265 is not feasible at the moment, perhaps a quicker solution would be to simply allow forwarding of the incoming signal. There is a passthrough feature, but as far as I understand, it passes the re-encoded stream to YouTube.

**_Restreamer Reencoded HDR stream nerd stats_**
![image](https://user-images.githubusercontent.com/8720442/235328369-f9ed4667-5e1a-40f2-9842-0de435a70148.png)

**_HDR Enabled nerd stats_**
![image](https://user-images.githubusercontent.com/8720442/235328362-7238d6a4-06b8-4642-9daf-9182c888d36c.png)

**Additional context**
Please check out this HDR Livestream. It looks really fantastic, especially if you have HDR enabled on your phone or monitor. [Link to the HDR Livestream](https://www.youtube.com/watch?v=i-PeirRr8bI&ab_channel=Rambalac)

Thank you for your attention to this matter. I appreciate your help in improving the streaming experience for creators and viewers alike.

**Comment by svenerbeck** [comment]
Hello roulendz,

Thank you for your feature request. It is a good point. We have added it to the official feature request list. https://github.com/datarhei/restreamer/discussions/345

To be honest: This feature is not on our 2023 roadmap.

There are several ways to achieve this goal:

**GitHub Pull Request:** The fastest and easiest way is to develop the feature and submit a pull request on GitHub. We will incorporate your code into one of the upcoming releases.

**Sponsor the feature for the community:** If you urgently need this feature for a commercial application, you can sponsor its development. This can be done via [Open Collective](https://opencollective.com/datarhei) or [Patreon](https://www.patreon.com/datarhei), for example. If you prefer other methods, we will work together to find a solution that works for you. So that you know, this extension would require 2 to 4 days of development time for a software developer to integrate it into Restreamer.

**Feature request on GitHub:** This is the least confident and slowest approach to requesting the feature. We may eventually develop the feature, but a specific timeframe or guarantee has yet to be set. You can add your request by commenting on our feature list: https://github.com/datarhei/restreamer/discussions/345

We appreciate your interest and contributions to the project.

Cheerio
Sven

**Comment by svenerbeck** [comment]
Hello @roulendz 

We are closing your ticket https://github.com/datarhei/restreamer/issues/552.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

**Comment by hereisderek** [comment]
I am able to get h265 steam working (i think). by first setting it to stream h264 in obs and set to passthrough in restreamer, then switch to stream h265.
still trying to figure out this hdr thingy but might have worked just need to tweak tone mapping on non-hdr

only drawback so far is that the preview in restreamer isn't working, but you can always use hls link and play on an external player

![image](https://github.com/datarhei/restreamer/assets/839795/ac492957-50fc-4589-95fb-bf77868a4329)

**Comment by danitus13** [comment]
> Sono in grado di far funzionare Steam h265 (credo). impostandolo prima sullo streaming h264 in obs e impostandolo su passthrough in restreamer, quindi passa allo streaming h265. sto ancora cercando di capire questa cosa dell'hdr ma potrebbe aver funzionato, devo solo modificare la mappatura dei toni su non-hdr
> 
> l'unico inconveniente finora è che l'anteprima nel restreamer non funziona, ma puoi sempre utilizzare il collegamento hls e giocare su un lettore esterno
> 
> ![Immagine](https://user-images.githubusercontent.com/839795/278153930-ac492957-50fc-4589-95fb-bf77868a4329.png)

hi I can't use OBS.
I use a Raspberry to stream 24 hours a day on Youtube, a Reolink 4K webcam which has H265 encoding.
The raspberry is not very powerful, so it is not able to switch from h265 to h264: freezing
So I need restreamer to support h265 directly
