### ISSUE TITLE
ABR playlist

### ISSUE THREAD

**Issue by openaspace** [datarhei/restreamer#553]
Hello.
I stream for the same video a 1080p and 576p rtmp stream.
I need to output an ABR playlist including both stream for autoselection bandwidth.

It's possibile to aggregate two streams server side?

**Comment by svenerbeck** [comment]
Hello openaspace,

Currently, this feature is not available in the community version of Restreamer. However, it has been added to the feature request list, and you can follow the discussion on this topic at the following link:

https://github.com/datarhei/restreamer/discussions/345

However, it is worth checking for any updates since then. You can always watch the Restreamer GitHub repository for the latest information and feature updates.

Cheerio
Sven

**Comment by svenerbeck** [comment]
Hello @openaspace 

We are closing your ticket https://github.com/datarhei/restreamer/issues/553.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
