### ISSUE TITLE
Audio options none not available

### ISSUE THREAD

**Issue by thebaz67** [datarhei/restreamer#565]
Just starting out and I have run into what I think is a bug.  I first set up a network camera to grab a feed. I use the wizard and I can select no audio.

If I then try to change the advanced settings on the camera I am forced to add an audio stream rather than no audio at all.

**Comment by svenerbeck** [comment]
We only process tickets with error logs. It is necessary, especially in your case, to see the error. Here you can see how to get the log file: https://www.youtube.com/watch?v=mZMGrweFCsM — Thank you for your understanding.

Cheerio Sven

** 
EDIT: The audio quality from surveillance cameras can often become problematic due to various factors. One common issue is the audio output from the camera itself. Many cameras operate without amplifiers and use outdated or unusual audio formats that were common during the early days of telephone technology.

We recommend using a modern audio format such as MP3 or AAC for the best possible audio quality. These formats offer superior sound quality and are widely compatible with various devices and software.

To assist you further with this issue, please provide us with the specific model of your camera. This information will allow us to perform a more detailed analysis and give you a more tailored solution.

Thank you for being so understanding, and we look forward to resolving this issue for you.
**

**Comment by thebaz67** [comment]
There is no error to report, I do not want to encode or restream any audio, when I use the wizard it allows me to set up no audio as an option.  If I try to use the advanced settings no audio is not an option only silence.

I am trying to not include any audio in the stream so MP3 or ACC does not matter.

![image](https://github.com/datarhei/restreamer/assets/133791940/d3f50cbe-1122-479d-9cc5-7ab1d4441e2d)


![image](https://github.com/datarhei/restreamer/assets/133791940/04072799-e23e-4674-98ca-7c86104e2fe3)
![image](https://github.com/datarhei/restreamer/assets/133791940/94fc36d2-8aec-417e-9bf0-ac482f2b59e1)
[report.txt](https://github.com/datarhei/restreamer/files/11534478/report.txt)

**Comment by thebaz67** [comment]
if I use the wizard I get this option

![image](https://github.com/datarhei/restreamer/assets/133791940/3efdca49-677a-4018-a179-5b555711b65a)

Which does not seem to be available when I use the advanced settings.

**Comment by ioppermann** [comment]
In the advanced settings you should see the "No Audio" option next to the network and virtual source:
![image](https://github.com/datarhei/restreamer/assets/57445/cf086019-57f0-4b84-b414-1e3ed5bfd233)

**Comment by svenerbeck** [comment]
Hello @thebaz67 

We are closing your ticket https://github.com/datarhei/restreamer/issues/565.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
