### ISSUE TITLE
How can I use OBS Studio with Restreamer ?

### ISSUE THREAD

**Issue by berserkwarwolf** [datarhei/restreamer#58]
When I try to connect from OBS Studio to restreamer, it doesn't work at all. It doesn't connect.

I tried another docker image named nginx-rtmp and it works flawlessly, but why doesn't Restreamer ? It's based on the same stack, so... what am I doing wrong ?

Has anyone tried using OBS + Restreamer ? Can someone please provide a step by step guide on how to use this combo ?

**Comment by svenerbeck** [comment]
This is an interesting setup. We are currently reworking the Restreamer. 
I will think of the instructions in this step. 

Could you describe what you would like to do or what your idea is with the connection?

I have never used OBS myself. But according to the logic of the Restreamer:
1. create your video input and start it
2. enter your OBS video input source and start it

Since I don't know OBS, it's only a way that could work if OBS allows for RTSP reception from external sources, I would try to go that way.

I will install OBS myself and test it after the next software update in summer or write the instructions for it.

Regards, and thank you for your patience.
Sven

**Comment by ioppermann** [comment]
This is a follow-up.

A similar case where someone wanted to push a RTMP stream to Restreamer is mentioned here:

https://github.com/datarhei/restreamer/issues/85#issuecomment-474874337

Please apply the changes to Docker command line as mentioned in the link above. Then in OBS you have to use the following stream settings:

Service: `Custom ...`
Server: `rtmp://[IP of your Restreamer]/live`
Stream Key: `external.stream?token=...`
