### ISSUE TITLE
How to manipulate the channels area by an external application?

### ISSUE THREAD

**Issue by daquadra** [datarhei/restreamer#595]
How to manipulate the channels area by an external application? Any idea? I would need to work with the channels directly and I saw that the API does not support this.

**Comment by ioppermann** [comment]
I will describe a bit how it works currently.

**Disclaimer: This is neither an official description nor a documentation and is subject to change in the future.**

The UI is using the API of the [Core](datarhei/core) which is documented here: https://docs.datarhei.com/core/

A channel in the UI is a process with an ID of a specific pattern: `restreamer-ui:ingest:` followed by an UUID. The UUID is the channel ID. The details about that channel is stored in the process' metadata under the key `restreamer-ui`.

Similar for publication services. The process ID has the pattern: `restreamer-ui:egress:[publication]:` followed by an UUID. The `[publication]` is the name of one of the publication services, e.g. `youtube`, `facebook`. The reference in the process config has to be the UUID of the ingest process (i.e. channel ID). The details about the egress is stored in its metadata.

The respective metadata contains JSON data structures the UI uses in order to display the settings.
