### ISSUE TITLE
snapshot interval change not accepted

### ISSUE THREAD

**Issue by INDAVO** [datarhei/restreamer#60]
Hello,

I use restreamer on Docker for Windows (Win10 x64 1803) via Kitematic and a Hyper-V machine.
All works perfect IO get a stream except for the snapshot interval settings.

I got a problem with restreamer environment variables adjustments.
I wanted to shorten the interval from 60 seconds (default) to 10 seconds (10000).
I tried to changed the environment variables add "SNAPSHOT_REFRESH_INTERVAL=10000" to the container and also tried "RS_SNAPSHOT_REFRESH_INTERVAL=10000".

The change is shown in the log:

![grafik](https://user-images.githubusercontent.com/40394932/41601629-3dc0ca78-73d9-11e8-9823-212590088026.png)

but as you can see the snapshots are still taken after an interval of 60 seconds. Nothing changes.

Can you help me? Do I need to edit this setting anywhere else?

**Comment by ioppermann** [comment]
This could be a bug. We will inventigate this.

**Comment by ioppermann** [comment]
This was actually a bug. If you specify the snapshot interval in milliseconds (in your case 10000), it will not be accepted (it has to be at least 30001 milliseconds). If you specify it as "10s", then it will be accepted. You should set the environment variable like this: "RS_SNAPSHOT_REFRESH_INTERVAL=10s". However values lower than 10 seconds will not be accepted.

This will be fixed in the next version.
