### ISSUE TITLE
host:8080 page not opening after weeks ago

### ISSUE THREAD

**Issue by nscpro** [datarhei/restreamer#604]
It's showing this message

{"code":404,"message":"File not found","details":["/index.html"]}

**Comment by seejm** [comment]
I think this happens because you dont have the playsite the restreamer turned on.  To get to Restreamer try http://youripadresss:8080/ui

**Comment by svenerbeck** [comment]
Hello @nscpro,

@seejm is correct. The issue is related to not having the admin site for the Restreamer activated. You can access Restreamer by navigating to http://youripaddress:8080/ui.

A big thank you to @seejm for the prompt and accurate assistance. We genuinely appreciate community members like you who step in to help. [electronic hanshake]

Cheerio,
Sven
