### ISSUE TITLE
 IRL PRO - RTMP - h265 not working

### ISSUE THREAD

**Issue by donmortis** [datarhei/restreamer#637]
Using a Samsung S9+ (plus) device with "IRL PRO," I'm unable to receive h265 data via an RTMP connection. If I initiate the "probe" button while there's an active stream and stream in h264, everything works perfectly. However, when I do the same with h265, the probe doesn't function, and it doesn't offer encoding options. Meanwhile, SRT streaming works smoothly with the same software and phone pairing. In IRL Pro, there is a switch that suggests that if I want to stream h265 via RTMP, I need to enable it separately in the "advanced" settings; otherwise, it won't allow streaming. I don't know the reason for this, but I need to be able to use h265. In both cases, I directly play the SRT and RTMP streams in OBS. Everything works flawlessly with SRT.

**Comment by ioppermann** [comment]
The RTMP protocol doesn't support H265 by default. There's an extension to the protocol specification available that allows H265, VP9, and AV1 with RTMP (this is probably meant by "advanced" settings). However, Restreamer doesn't support this extension yet.

**Comment by svenerbeck** [comment]
Hello @donmortis 

We are closing your ticket https://github.com/datarhei/restreamer/issues/637.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!

**Comment by Zenturier** [comment]
Hello,

please tell me how you connect from IRL Pro App to Restreamer.
I trye now many days, it wont work. 
I tryed SRT and RTMP.
In my Restreamer (at a P4 running) I trye to add the source but no way.
Also I not know the correct settings in IRL Pro App because there is no custom Setting Button....

Thanks
