### ISSUE TITLE
SRT not recconect and high unstable bandwith

### ISSUE THREAD

**Issue by donmortis** [datarhei/restreamer#640]
I'm currently streaming with IRL Pro using both an S10+ and an S9+ phone, and the SRT stream doesn't reconnect automatically. If the signal is lost, the software on the phone displays the bitrate in red, and I have to stop the stream and restart it for the SRT stream to work again. This is problematic because I have to make adjustments to the phone mounted on my chest, and I only notice that the stream isn't working when viewers alert me. I experienced this issue while streaming in h265, and I haven't had the opportunity to test it in h264 yet.

**Comment by ioppermann** [comment]
@donmortis Please try the `datarhei/restreamer:dev` docker image. This fixes some SRT related issues.

**Comment by svenerbeck** [comment]
Hello @donmortis 

We are closing your ticket https://github.com/datarhei/restreamer/issues/640.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
