### ISSUE TITLE
On Docker restart: Failed to refresh token: Missing or invalid JWT token

### ISSUE THREAD

**Issue by tjcooney** [datarhei/restreamer#643]
Whenever docker restarts and restreamer boots up, the settings are all wiped and this message appears in the corner:
**Failed to refresh token: Missing or invalid JWT token**

Any advice on how to resolve this? Currently running on Windows. I've tried re-installing restreamer and docker, and I get the same result.

**Comment by ioppermann** [comment]
It seems that your config has not been properly persisted to your disk. In order to persist the config to your disk (and thus being re-used after restart), you have to define volumes in the settings for the Restreamer container. Please follow step 6 in the [documentation for settings up Restreamer under Windows](https://docs.datarhei.com/restreamer/installing/windows#step-6-configurate-your-restreamer-container-and-start).

**Comment by svenerbeck** [comment]
Hello @tjcooney 

We are closing your ticket https://github.com/datarhei/restreamer/issues/643.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
