### ISSUE TITLE
Https Let's Encrypt certification doesn't work

### ISSUE THREAD

**Issue by LuizStSantos** [datarhei/restreamer#652]
I have a problem, I can't use HTTPS even though I followed the video I opened the ports on my router and in Docker I pointed to 80:8080 and 443:8181 and on my router I opened ports 443 and 80 to the machine that hosts the Restreamer and it's not working, I've already activated the functions within Restreamer too and it doesn't work, I followed the video step by step only HTTP is working.
My Domain only points to the server that is only the Restreamer

[report.txt](https://github.com/datarhei/restreamer/files/13581767/report.txt)

**Comment by ioppermann** [comment]
Your domain has to point to the public IP of your router.

**Comment by svenerbeck** [comment]
Hello  @LuizStSantos 

We are closing your ticket https://github.com/datarhei/restreamer/issues/652.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
