### ISSUE TITLE
Where can I find the Environment Variables

### ISSUE THREAD

**Issue by SarahDal** [datarhei/restreamer#659]
**Subject of the issue**
The list of Environment Variables is missing? I previously used the last version of Restreamer from the command line of a headless pi, enabling me to stop and start streams in crontab. I would like to do this with v2 of restreamer.

**Your environment**
Restreamer is running on RPi 3B+ with Raspicam
Linux desktop on PC with which I am trying to view the repo file

**Steps to reproduce**
Go to https://docs.datarhei.com/restreamer/installing/raspberry-pi-arm
click the link for "List with all available environment variables"
It takes you to the repo for core, but I cannot see any list of environmental variables.
Searching all of datarhei for "environment-variables" returns nothing

**Comment by ioppermann** [comment]
The link was broken. It is fixed now and leads to https://docs.datarhei.com/restreamer/api/environment-variables

**Comment by svenerbeck** [comment]
Hello @SarahDal 

We are closing your ticket https://github.com/datarhei/restreamer/issues/659.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
