### ISSUE TITLE
Adding already generated cert manually.

### ISSUE THREAD

**Issue by brokendash** [datarhei/restreamer#663]
Hello I'm attemping to add my already generated cert file and I'm having issues....please provide some basic guidance....

Executing this from cmd line.

 docker run  --detach --rm --name core --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest --env CORE_TLS_ENABLE=true --env CORE_TLS_CERTFILE=/etc/letsencrypt/live/neogenic.org/cert.pem --env CORE_TLS_KEYFILE=/etc/letsencrypt/live/neogenic.org/privkey.pem

**Comment by ioppermann** [comment]
You have to mount the directory into the Docker container. You can do it like this:

docker run --detach --rm --name core --volume /opt/core/config:/core/config --volume /opt/core/data:/core/data **--volume /etc/letsencrypt/live/neogenic.org:/cert** --publish 8080:8080 --publish 8181:8181 --publish 1935:1935 --publish 1936:1936 --publish 6000:6000/udp datarhei/restreamer:latest --env CORE_TLS_ENABLE=true **--env CORE_TLS_CERTFILE=/cert/cert.pem** **--env CORE_TLS_KEYFILE=/cert/privkey.pem**

**Comment by svenerbeck** [comment]
Hello @brokendash 

We are closing your ticket https://github.com/datarhei/restreamer/issues/663.

This may be due to the following reasons:

- Problem/inquiry has been solved
- Ticket remained unanswered by you for a more extended period
- Problem was explained and handled in another ticket

You can reopen this ticket at any time!

Please only open related tickets once! Always answer/ask in the original ticket with the same issue!
