### ISSUE TITLE
Docker setup causing undue wear of Raspberry Pi SD Card

### ISSUE THREAD

**Issue by TheOriginalMrWolf** [datarhei/restreamer#81]
Hi,

First, thanks so much for such a fabulous tool!!

I've set up as per instructions on a Raspberry Pi 3, with docker and your datarhei/restreamer-armv7l:latest image (note, the instructions point to an image that's no longer there).

Everything worked perfectly, but I noticed using iotop that there was significant write activity to the SD card.

Turns out that nginx-rtmp is writing many small (ie 20k) video files (eg: live.stream-2047.ts) continuously to /tmp/hls in the docker container (basically, streaming the last couple of minutes of video to files).  

Since /tmp isn't mounted on tmpfs in the docker image (unlike the Pi itself where I've set up tmp on tmpfs), this ended up getting written to SD.  Totally doesn't make sense as only a couple of minutes of video are stored in a short queue before the oldest file is erased.

Naturally, this sort of undue high wear isn't great to do on a Raspberry's SD card, and will probably result in premature failure.

Since I'm only new to Docker, wasn't too sure as to the 'best' way to deal with this, so all I did was map the Pi's /tmp through to the docker image: -v /tmp:/tmp.

So now I get 0 disk writes and a little less CPU.

Can someone who knows what they're doing please have a look and suggest the 'right' way to deal with this?

Thanks again!!!

**Comment by ioppermann** [comment]
Hi

Thanks for your comment and for the hint with the wrong references to the ARM32v7 docker images.

Inside of the docker container it is not possible to mount a tmpfs because docker removes the mount privileges. This would only work if the `docker run ...` command is called with the `--privileged` option. However, this is not adviseable for the regular Restreamer operation as it allows to mount anything from inside the docker container.

The way you solved the problem does its job. But there is a more "official" way that doesn't require you to setup a tmpfs on the host system:

`docker run ... --tmpfs /tmp/hls ...`
or (as of docker 17.06)
`docker run ... --mount type=tmpfs,destination=/tmp/hls ...`

For more details on these commands, please read https://docs.docker.com/storage/tmpfs/

**Comment by TheOriginalMrWolf** [comment]
So the question is: did anyone update the install instructions to help prevent everyone killing their Raspberry Pi's ???

**Comment by TheOriginalMrWolf** [comment]
Ahhh... yes you did.  So excellent.  Probably a good idea to really highlight that, otherwise there are going to be a lot of burnt-out SD cards.
