### ISSUE TITLE
Feature request: support x265

### ISSUE THREAD

**Issue by chwong1** [datarhei/restreamer#84]
Is it possible to support x265 / hevc encoding?

**Comment by chwong1** [comment]
I see, good to know that.

**Comment by ioppermann** [comment]
@chwong1 The latest Restreamer release allows to re-encode the stream, i.e. if your stream from the camera is encoded with x265, you can re-encode it to x264 in order to do HLS streaming.

**Comment by chwong1** [comment]
Great!

**Comment by strarsis** [comment]
@ioppermann: When the stream is relayed to YouTube, would it make sense to use H.264 from IPCam and use Restreamer in copy mode, or is it worth the extra conversion step and let Restreamer use a H.265 source?

**Comment by maiksd** [comment]
I'm using Larix Broadcaster which has HEVC support, and tried streaming that to Restreamer, both current versions, but Restreamer will complain the codec is 'unknown'. Not sure which side's the problem here, but I'd be happy to use HEVC because it would enable me to go back up to 1080p from the location where I have to stream from, where bandwidth is limited.

**Comment by ioppermann** [comment]
The only way to push a stream to Restreamer is currently only via RTMP. However, HEVC over RTMP is not officially supported by RTMP. The nginx-rtmp module is also not supporting it. Because of this the video data is then dropped/scrambled and you'll get the "unknown codec" error.

We're planning to support also SRT as a way to push to Restreamer. This is more future-proof.
