### ISSUE TITLE
Add audio stream validation

### ISSUE THREAD

**Issue by andrew-shulgin** [datarhei/restreamer#9]
Some sources do have an audio stream, but it is not AAC but PCM for example. Currenrtly Restreamer recognizes that stream as a valid audio stream and copies it to RTMP. It's wrong because HLS requires AAC audio stream.

There are two possible soultions:
- Transcode audio stream to AAC (preferred)
- Replace that stream with silent audio stream (as it is made for video-only streams)

**Comment by jstabenow** [comment]
Japp, it's a problem. 
We have to refactore the "detection" because it is just a check if there is more then one channel. But this can be e.g. a data stream. So we need a right audio/aac check.
Currently we can't implement futures like encoding/transcoding because arm-device are lowpowered. This will be a challenge after the first stable release.
Our focus will be on the FFmpeg implementation in RC7 and this problem will be a part of it. 
So we have to detect and overwrite a wrong audiochannel by an fakeaudio-option.

**Comment by andrew-shulgin** [comment]
In most cases, lowpower devices have enough power to transcode audio stream. And Restreamer is **already** transcoding /dev/null to AAC if audio stream is not present.

**Comment by jstabenow** [comment]
Yes it's right, but this was a tested case and /dev/null is not a real encoding ;-)
Did you have the needed experience and know the cpu load of different cases for e.g. ARMv6l? If, we can implement it.

**Comment by andrew-shulgin** [comment]
I'll test it on `RaspberryPi B` soon to make sure and let you know

**Comment by jstabenow** [comment]
Perfect, thanks :+1:
