### ISSUE TITLE
Continue existing YouTube stream

### ISSUE THREAD

**Issue by strarsis** [datarhei/restreamer#90]
Is it possible to continue streaming to an existing YouTube stream?

**Comment by ioppermann** [comment]
Hi

This is a bit tricky. For this you should setup a live streaming event in the [live dashboard](https://www.youtube.com/live_dashboard). The normal "Stream now" will create a new video ID after the stream got interrupted.

By creating a live event, you can have interruption in pushing the stream by keeping the same video ID.

However, Youtube sometimes and randomly may stop the event and mark it as completed. If you keep pushing the stream, it will not continue the event. You have to create a new event (which will create also a new video ID) in order to continue streaming.
