### ISSUE TITLE
External stream (YouTube): No data

### ISSUE THREAD

**Issue by strarsis** [datarhei/restreamer#91]
Local player works (connection between IPCamera and raspberry with restreamer is over Ethernet) but external stream bandwidth is around 0.5Kb/s and YouTube Stream preview first states "Very good connection", then "No data" and "Weak connection" with no preview image.

````
Streaming is successfully initiated.
26 FPS / 0.5 Kb/s
````
Internet uplink is 10Mbit/s which should be enough for a Full HD (~8Mbit/s) stream.

Edit: Rechecked restreamer UI after some hours and then the YouTube stream bandwidth went up to 
more than 1000Kb/s, but YouTube still waits for video and states that connection is weak.

**Comment by ioppermann** [comment]
You have to consider the effective bandwidth that is available to the Google RTMP ingestor. It may have less than 10 or 8Mbit/s because it gets routed through your ISP and other hops.

Also with an uplink of 10Mbit/s, the available bandwidth for the payload (the video stream) is usually less because of the overhead from the protocol layers.

Please also check the following recommendations from Google for the resolution and bandwidth settings for a live stream: https://support.google.com/youtube/answer/2853702?hl=en

Google recommends 3-6Mbit/s for a FullHD stream @25-30fps.

Please try with a lower bandwidth and experiment how much is possible.

**Comment by ioppermann** [comment]
One more thing: Youtube requires that the stream has an audio track (preferrably AAC). To add an audio track or to overwrite an existing audio track with silence, you have to start the Docker container with the `RS_AUDIO` environment variable set to `silence`, e.g. `docker run ... -e RS_AUDIO=silence ...`.

If the stream of the camera already has an audio track which is not encoded as AAC, then you have to convert it by setting the `RS_AUDIO` environment variable to `aac`.

**Comment by strarsis** [comment]
@ioppermann: I set `RS_AUDIO` to `aac` for being sure the audio is right.
I access restreamer via SSH tunnel, could this somehow confuse restreamer?

YouTube tries to load a preview, connection is 'Very Good Connection' and 
the external stream speed goes up until it reaches expectable speed for FullHD.

How can I further diagnose why YouTube is unable to load a preview from that stream?
Are there external diagnosis RTMP streaming servers that just accept a RTMP stream and 
report its suitability for being used as YouTube Live Stream?

**Comment by ioppermann** [comment]
Accessing Restreamer via SSH tunnel should not pose a problem.

You can enable the debug mode of Restreamer by adding `-e RS_DEBUG=true` to the Docker command line. This wil extensively log the output of the internal ffmpeg. You'll find the logs in `http://[IP of your Restreamer]/debug/`. This will give more clues about what is happening.

You can also push the stream back to Restreamer's internal RTMP Server. You can do this by providing this URL for the external RTMP-Server (instead of Youtube): `rtmp://127.0.0.1:1935/live/youtube.stream`.

The you can check the stream by either playing its HLS stream `http://[IP of your Restreamer]/hls/youtube.stream.m3u8` or by playing the RTMP stream (with VLC or ffplay) from `rtmp://127.0.0.1:1935/live/youtube.stream`.

For the second option to work, you have to expose the RTMP port of the Restreamer container by adding this to your Docker command line: `docker run ... -p 1935:1935 ...`. However this exposes the RTMP server of Restreamer. In case the your Restreamer is publicly accessible, you should protect the RTMP server with a token: `docker run ... -p 1935:1935 -e RS_TOKEN=somerandomstring ...`. Then you have add `?token=somerandomstring` to the RTMP URLs that point to the Restreamer.

Can you give me more specs about the stream that you are pulling from your IPCamera? Is it possoble that you give me access to the stream so I can test it out?

**Comment by strarsis** [comment]
@ioppermann: Restarted the docker container (also for setting `RS_DEBUG=true`) and then 
noticed that YouTube suddently shows a preview and that stream can be started.

During the stream I get the following warning in YouTube:
````
Error
Your encoder is sending data faster than realtime (multipleseconds of video each second). You must rate limit your livevideo upload to approximately 1 second of video each second.
````

**Comment by ioppermann** [comment]
According to the warning, the bitrate should be around 4500 Kbps. This is in the recommended range (see the link in my first reply). Try to configure your camera accordingly. Restreamer is currently not doing any re-encoding of the stream. It just forwards the stream as it receiveves it from the camera.

Youtube requires that 1) the stream has an audio track and 2) the audio track has to be either AAC or MP3.

The `RS_DEBUG=true` setting's purpose is to have access to the logs from ffmpeg in order to see where the problem might be. It doesn't change anything in how the stream data is handled. For normal operation you should not use the debug mode because it writes a lot of data to the disk which may get full at some point.

**Comment by strarsis** [comment]
@ioppermann: So I set `RS_AUDIO=aac` and it fixed the audio warning by YouTube.
Also set the stream bandwidth of camera to max. value (8000).
Now the YouTube stream looks fine and FullHD also works.
It appears that YouTube also changed something with the Streaming (Beta) and this helped, too.

Thank you for your help!
