### ISSUE TITLE
feasibility question

### ISSUE THREAD

**Issue by philipptrenz** [datarhei/restreamer#99]
Hey there, 

thanks for your great project! I read the documentation, but I'm still not sure if Restreamer can archive what I'm looking for. That's why I want to ask for some advice. 

So here's my use case:
- Goal: Provide a publicly available 24/7 live stream embedded in a website (https)
- Having a RTSP stream url from a security camera available from within the local network
- The ISP does not provide a static IP, so DynDNS is not an option
- I have server resources within the local network (NAS with Docker) as well as publicly available (cloud instance with static IP)

Can you outline a way for me to achieve my goal? Setting up servers, writing Dockerfiles, configuring nginx and ffmpeg is not a problem for me and I just need a tip in the right direction ;)

Thanks in advance!

**Comment by ioppermann** [comment]
Hi Philipp

What you describe, Restreamer is made for.

With Restreamer comes a player that is embeddable in websites, similar to Youtube videos (iframe). You can also configure Restreamer to use a TLS certificate that you provide in order to enable https.

https://datarhei.github.io/restreamer/docs/guides-embedding.html
https://datarhei.github.io/restreamer/docs/guides-https.html


The usual setup is that Restreamer runs on a machine in your local network where also the camera is in. So you can run the Restreamer docker image on your NAS. Then you tell Restreamer where to pull from the RTSP stream. That‘s it. In the management interface of Restreamer (can be accessed with any browser) you‘ll find the URL of the player that you can embed in other sites.

https://datarhei.github.io/restreamer/docs/installation-linux-64.html

Regarding the changing IP address, any DynDNS is actually the solution. Either your router already supports a DynDNS provider or you create some kind of a cronjob that updates your current IP at the DynDNS service.

https://datarhei.github.io/restreamer/wiki/dynamic-dns.html

**Comment by philipptrenz** [comment]
Hi @ioppermann,

thanks for the quick reply and the explanations. 

I understood the documentation up to this point, but, as you may have overlooked, my problem is, that the local network is behind a NAT and does not get any public IP assigned by the ISP.

**Comment by ioppermann** [comment]
OK, I understand. For the NAT situation you can use the „port forwarding“ settings of your router.

As an other option, you could run a second Restreamer on your public cloud instance and use the Restreamer in your local network to forward the stream to the second Restreamer, i.e. the second Restreamer acts as an external RTMP server. Check out this issue to make the second Restreamer listen to RTMP streams: https://github.com/datarhei/restreamer/issues/85

**Comment by philipptrenz** [comment]
Perfect, that is what I was looking for!

Could I, instead of the local Restreamer, just use ffmpeg to redirect the provided `RTSP over TCP` url to the cloud instance as I do not need the other Restreamer features from within my network?

Thanks!

**Comment by ioppermann** [comment]
Yes, it is also possible to use ffmpeg (or any thing else that can push a stream to a RTMP server). In this case ffmpeg needs the output options „-f flv rtmp://[ip of your public instance]/live/...“ and the input is the RTSP over TCP URL with stream copy to avoid any processing, i.e. „-codec copy“.

**Comment by philipptrenz** [comment]
Perfect! I summarized the procedure. Even though I have not tested it yet, I share my findings here for anyone who has similar things in mind: 



### Step 1: Install Restreamer Docker image on a cloud instance

Inside the Restreamer Docker container is a RTMP-Server running (nginx-rtmp) that you can use to push streams to. To have access to the RTMP-Server, you have to expose the port 1935 of the Docker container. 

You should secure your stream with an token, so that only you can stream to the Restreamer instance. Also change credentials by setting it via enviroment variables.

Start the container with:

```bash
docker run -d --restart always \
	--name restreamer \
	-e "RS_USERNAME=[your_username]" -e "RS_PASSWORD=[your_password]" -e "RS_TOKEN=[stream_token]" \
	-p 8080:8080 -p 1935:1935 -v /mnt/restreamer/db:/restreamer/db \
	datarhei/restreamer:latest
```

### Step 2: Push local stream to Restreamer cloud instance

Use a local instance of restreamer and configure the *External RTMP-Streaming-Server* to `rtmp://[url_of_restreamer_cloud_instance]/live/external.stream?token=[stream_token]`

__OR__

just use ffmpeg:

```bash
ffmpeg -i 'rtsp://[rtsp_or_rtmp_url_from_local_device]' -codec copy -f flv rtmp://[url_of_restreamer_cloud_instance]/live/external.stream?token=[stream_token]
```

### Step 3: Configure Restreamer and start streaming

Navigate to the Restreamer web interface at`http://[url_of_restreamer_cloud_instance]:8080/`.

For the video source enter the same address you are pushing to, and replace the public address and port with localhost:

```
rtmp://localhost/live/external.stream?token=[stream_token]
```

Now you can forward it to an other RTMP-Server or embed the player in a website.
